// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"errors"
	"math"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _ImagingStats_desired_images(ctx context.Context, field graphql.CollectedField, obj *model.ImagingStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ImagingStats_desired_images(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.DesiredImages, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ImagingStats_desired_images(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ImagingStats", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ImagingStats_accepted_images(ctx context.Context, field graphql.CollectedField, obj *model.ImagingStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ImagingStats_accepted_images(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.AcceptedImages, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ImagingStats_accepted_images(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ImagingStats", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ImagingStats_rejected_images(ctx context.Context, field graphql.CollectedField, obj *model.ImagingStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ImagingStats_rejected_images(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.RejectedImages, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ImagingStats_rejected_images(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ImagingStats", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ImagingStats_acquired_images(ctx context.Context, field graphql.CollectedField, obj *model.ImagingStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ImagingStats_acquired_images(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.AcquiredImages, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ImagingStats_acquired_images(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ImagingStats", field, false, false, errors.New("field of type Int does not have child fields"))
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var imagingStatsImplementors = []string{"ImagingStats"}

func (ec *executionContext) _ImagingStats(ctx context.Context, sel ast.SelectionSet, obj *model.ImagingStats) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, imagingStatsImplementors)

	out := graphql.NewFieldSet(fields)
	deferredFieldSet := graphql.NewFieldSet(nil)
	deferLabelToView := make(map[string]*graphql.FieldSetView)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("ImagingStats")
		case "desired_images":
			out.Values[i] = ec._ImagingStats_desired_images(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "accepted_images":
			out.Values[i] = ec._ImagingStats_accepted_images(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "rejected_images":
			out.Values[i] = ec._ImagingStats_rejected_images(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "acquired_images":
			out.Values[i] = ec._ImagingStats_acquired_images(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferLabelToView), math.MaxInt32)))

	ec.ProcessDeferredGroup(graphql.DeferredGroup{
		Defers:   deferLabelToView,
		Path:     graphql.GetPath(ctx),
		FieldSet: deferredFieldSet,
		Context:  ctx,
	})

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) marshalNImagingStats2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐImagingStats(ctx context.Context, sel ast.SelectionSet, v *model.ImagingStats) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._ImagingStats(ctx, sel, v)
}

func (ec *executionContext) unmarshalNORDER_DIRECTION2githubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOrderDirection(ctx context.Context, v any) (model.OrderDirection, error) {
	var res model.OrderDirection
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNORDER_DIRECTION2githubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOrderDirection(ctx context.Context, sel ast.SelectionSet, v model.OrderDirection) graphql.Marshaler {
	return v
}

// endregion ***************************** type.gotpl *****************************
