// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"errors"
	"math"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

type OtherTargetResolver interface {
	Cover(ctx context.Context, obj *model.OtherTarget) (*model.ProjectCover, error)
	Masters(ctx context.Context, obj *model.OtherTarget) ([]*model.FilterMaster, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _OtherTarget_name(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_name(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Name, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_name(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _OtherTarget_lights(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_lights(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Lights, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_lights(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _OtherTarget_recorded(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_recorded(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Recorded, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_recorded(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _OtherTarget_stacked(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_stacked(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Stacked, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_stacked(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _OtherTarget_nights(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_nights(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Nights, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_nights(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _OtherTarget_first_night(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_first_night(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.FirstNight, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *string) graphql.Marshaler {
			return ec.marshalOString2ᚖstring(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_first_night(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _OtherTarget_last_night(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_last_night(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.LastNight, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *string) graphql.Marshaler {
			return ec.marshalOString2ᚖstring(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_last_night(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("OtherTarget", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _OtherTarget_cover(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_cover(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.OtherTarget().Cover(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *model.ProjectCover) graphql.Marshaler {
			return ec.marshalOProjectCover2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectCover(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_cover(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "OtherTarget",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_ProjectCover(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _OtherTarget_masters(ctx context.Context, field graphql.CollectedField, obj *model.OtherTarget) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_OtherTarget_masters(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.OtherTarget().Masters(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []*model.FilterMaster) graphql.Marshaler {
			return ec.marshalNFilterMaster2ᚕᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐFilterMasterᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_OtherTarget_masters(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "OtherTarget",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_FilterMaster(ctx, field)
		},
	}
	return fc, nil
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var otherTargetImplementors = []string{"OtherTarget"}

func (ec *executionContext) _OtherTarget(ctx context.Context, sel ast.SelectionSet, obj *model.OtherTarget) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, otherTargetImplementors)

	out := graphql.NewFieldSet(fields)
	deferredFieldSet := graphql.NewFieldSet(nil)
	deferLabelToView := make(map[string]*graphql.FieldSetView)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("OtherTarget")
		case "name":
			out.Values[i] = ec._OtherTarget_name(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "lights":
			out.Values[i] = ec._OtherTarget_lights(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "recorded":
			out.Values[i] = ec._OtherTarget_recorded(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "stacked":
			out.Values[i] = ec._OtherTarget_stacked(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "nights":
			out.Values[i] = ec._OtherTarget_nights(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "first_night":
			out.Values[i] = ec._OtherTarget_first_night(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "last_night":
			out.Values[i] = ec._OtherTarget_last_night(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "cover":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._OtherTarget_cover(ctx, field, obj)
				if res == graphql.RequiredNull {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "masters":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._OtherTarget_masters(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferLabelToView), math.MaxInt32)))

	ec.ProcessDeferredGroup(graphql.DeferredGroup{
		Defers:   deferLabelToView,
		Path:     graphql.GetPath(ctx),
		FieldSet: deferredFieldSet,
		Context:  ctx,
	})

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) marshalNOtherTarget2ᚕᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOtherTargetᚄ(ctx context.Context, sel ast.SelectionSet, v []*model.OtherTarget) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return ec.marshalNOtherTarget2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOtherTarget(ctx, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

func (ec *executionContext) marshalNOtherTarget2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOtherTarget(ctx context.Context, sel ast.SelectionSet, v *model.OtherTarget) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._OtherTarget(ctx, sel, v)
}

func (ec *executionContext) marshalOOtherTarget2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOtherTarget(ctx context.Context, sel ast.SelectionSet, v *model.OtherTarget) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	return ec._OtherTarget(ctx, sel, v)
}

// endregion ***************************** type.gotpl *****************************
