// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"errors"
	"math"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

type ProjectResolver interface {
	Targets(ctx context.Context, obj *model.Project) ([]*model.Target, error)
	Stats(ctx context.Context, obj *model.Project) (*model.ProjectStats, error)
	Mosaics(ctx context.Context, obj *model.Project) ([]*model.Mosaic, error)
	Cover(ctx context.Context, obj *model.Project) (*model.ProjectCover, error)
}
type ProjectStatsResolver interface {
	Imaging(ctx context.Context, obj *model.ProjectStats) (*model.ImagingStats, error)
	LastImageDate(ctx context.Context, obj *model.ProjectStats) (*int32, error)
	Plans(ctx context.Context, obj *model.ProjectStats) (int32, error)
	PlansMet(ctx context.Context, obj *model.ProjectStats) (int32, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _Project_id(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_id(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.ID, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int) graphql.Marshaler {
			return ec.marshalNID2int(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_Project_id(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type ID does not have child fields"))
}

func (ec *executionContext) _Project_profile_id(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_profile_id(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.ProfileID, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_Project_profile_id(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _Project_name(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_name(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Name, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_Project_name(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _Project_description(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_description(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Description, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *string) graphql.Marshaler {
			return ec.marshalOString2ᚖstring(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_description(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _Project_state(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_state(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.State, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *model.ProjectState) graphql.Marshaler {
			return ec.marshalOProjectState2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectState(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_state(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type ProjectState does not have child fields"))
}

func (ec *executionContext) _Project_priority(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_priority(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Priority, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *model.ProjectPriority) graphql.Marshaler {
			return ec.marshalOProjectPriority2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectPriority(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_priority(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type ProjectPriority does not have child fields"))
}

func (ec *executionContext) _Project_create_date(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_create_date(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.CreateDate, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_create_date(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_active_date(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_active_date(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.ActiveDate, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_active_date(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_inactive_date(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_inactive_date(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.InactiveDate, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_inactive_date(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_minimum_time(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_minimum_time(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.MinimumTime, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_minimum_time(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_minimum_altitude(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_minimum_altitude(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.MinimumAltitude, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *float64) graphql.Marshaler {
			return ec.marshalOFloat2ᚖfloat64(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_minimum_altitude(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Float does not have child fields"))
}

func (ec *executionContext) _Project_use_custom_horizon(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_use_custom_horizon(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.UseCustomHorizon, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *bool) graphql.Marshaler {
			return ec.marshalOBoolean2ᚖbool(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_use_custom_horizon(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Boolean does not have child fields"))
}

func (ec *executionContext) _Project_horizon_offset(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_horizon_offset(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.HorizonOffset, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *float64) graphql.Marshaler {
			return ec.marshalOFloat2ᚖfloat64(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_horizon_offset(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Float does not have child fields"))
}

func (ec *executionContext) _Project_meridian_window(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_meridian_window(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.MeridianWindow, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_meridian_window(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_filter_switch_frequency(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_filter_switch_frequency(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.FilterSwitchFrequency, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_filter_switch_frequency(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_dither_every(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_dither_every(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.DitherEvery, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_dither_every(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_enable_grader(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_enable_grader(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.EnableGrader, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *bool) graphql.Marshaler {
			return ec.marshalOBoolean2ᚖbool(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_enable_grader(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Boolean does not have child fields"))
}

func (ec *executionContext) _Project_is_mosaic(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_is_mosaic(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.IsMosaic, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *bool) graphql.Marshaler {
			return ec.marshalOBoolean2ᚖbool(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_is_mosaic(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Boolean does not have child fields"))
}

func (ec *executionContext) _Project_flats_handling(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_flats_handling(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.FlatsHandling, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_flats_handling(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_maximum_altitude(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_maximum_altitude(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.MaximumAltitude, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *float64) graphql.Marshaler {
			return ec.marshalOFloat2ᚖfloat64(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_maximum_altitude(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Float does not have child fields"))
}

func (ec *executionContext) _Project_smart_exposure_order(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_smart_exposure_order(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.SmartExposureOrder, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_smart_exposure_order(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("Project", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _Project_targets(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_targets(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Project().Targets(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []*model.Target) graphql.Marshaler {
			return ec.marshalNTarget2ᚕᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐTargetᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_Project_targets(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Project",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_Target(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _Project_stats(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_stats(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Project().Stats(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *model.ProjectStats) graphql.Marshaler {
			return ec.marshalNProjectStats2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectStats(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_Project_stats(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Project",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_ProjectStats(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _Project_mosaics(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_mosaics(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Project().Mosaics(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v []*model.Mosaic) graphql.Marshaler {
			return ec.marshalNMosaic2ᚕᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐMosaicᚄ(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_Project_mosaics(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Project",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_Mosaic(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _Project_cover(ctx context.Context, field graphql.CollectedField, obj *model.Project) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_Project_cover(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Project().Cover(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *model.ProjectCover) graphql.Marshaler {
			return ec.marshalOProjectCover2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectCover(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_Project_cover(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Project",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_ProjectCover(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _ProjectCover_palette(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_palette(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Palette, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_palette(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _ProjectCover_filter(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_filter(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Filter, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_filter(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _ProjectCover_preview_url(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_preview_url(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.PreviewURL, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_preview_url(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _ProjectCover_mosaic(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_mosaic(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Mosaic, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v bool) graphql.Marshaler {
			return ec.marshalNBoolean2bool(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_mosaic(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type Boolean does not have child fields"))
}

func (ec *executionContext) _ProjectCover_updated_at(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_updated_at(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.UpdatedAt, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v string) graphql.Marshaler {
			return ec.marshalNString2string(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_updated_at(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type String does not have child fields"))
}

func (ec *executionContext) _ProjectCover_panels(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_panels(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.Panels, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_panels(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ProjectCover_panels_total(ctx context.Context, field graphql.CollectedField, obj *model.ProjectCover) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectCover_panels_total(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return obj.PanelsTotal, nil
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_ProjectCover_panels_total(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectCover", field, false, false, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ProjectStats_imaging(ctx context.Context, field graphql.CollectedField, obj *model.ProjectStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectStats_imaging(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.ProjectStats().Imaging(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *model.ImagingStats) graphql.Marshaler {
			return ec.marshalNImagingStats2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐImagingStats(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectStats_imaging(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "ProjectStats",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.childFields_ImagingStats(ctx, field)
		},
	}
	return fc, nil
}

func (ec *executionContext) _ProjectStats_last_image_date(ctx context.Context, field graphql.CollectedField, obj *model.ProjectStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectStats_last_image_date(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.ProjectStats().LastImageDate(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v *int32) graphql.Marshaler {
			return ec.marshalOInt2ᚖint32(ctx, selections, v)
		},
		true,
		false,
	)
}
func (ec *executionContext) fieldContext_ProjectStats_last_image_date(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectStats", field, true, true, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ProjectStats_plans(ctx context.Context, field graphql.CollectedField, obj *model.ProjectStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectStats_plans(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.ProjectStats().Plans(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectStats_plans(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectStats", field, true, true, errors.New("field of type Int does not have child fields"))
}

func (ec *executionContext) _ProjectStats_plans_met(ctx context.Context, field graphql.CollectedField, obj *model.ProjectStats) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return ec.fieldContext_ProjectStats_plans_met(ctx, field)
		},
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.ProjectStats().PlansMet(ctx, obj)
		},
		nil,
		func(ctx context.Context, selections ast.SelectionSet, v int32) graphql.Marshaler {
			return ec.marshalNInt2int32(ctx, selections, v)
		},
		true,
		true,
	)
}
func (ec *executionContext) fieldContext_ProjectStats_plans_met(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	return graphql.NewScalarFieldContext("ProjectStats", field, true, true, errors.New("field of type Int does not have child fields"))
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

func (ec *executionContext) unmarshalInputProjectOrderBy(ctx context.Context, obj any) (model.ProjectOrderBy, error) {
	var it model.ProjectOrderBy
	if obj == nil {
		return it, nil
	}

	asMap := map[string]any{}
	for k, v := range obj.(map[string]any) {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"field", "direction"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "field":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("field"))
			data, err := ec.unmarshalNProjectOrderField2githubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectOrderField(ctx, v)
			if err != nil {
				return it, err
			}
			it.Field = data
		case "direction":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("direction"))
			data, err := ec.unmarshalNORDER_DIRECTION2githubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐOrderDirection(ctx, v)
			if err != nil {
				return it, err
			}
			it.Direction = data
		}
	}
	return it, nil
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var projectImplementors = []string{"Project"}

func (ec *executionContext) _Project(ctx context.Context, sel ast.SelectionSet, obj *model.Project) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, projectImplementors)

	out := graphql.NewFieldSet(fields)
	deferredFieldSet := graphql.NewFieldSet(nil)
	deferLabelToView := make(map[string]*graphql.FieldSetView)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("Project")
		case "id":
			out.Values[i] = ec._Project_id(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "profile_id":
			out.Values[i] = ec._Project_profile_id(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "name":
			out.Values[i] = ec._Project_name(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "description":
			out.Values[i] = ec._Project_description(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "state":
			out.Values[i] = ec._Project_state(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "priority":
			out.Values[i] = ec._Project_priority(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "create_date":
			out.Values[i] = ec._Project_create_date(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "active_date":
			out.Values[i] = ec._Project_active_date(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "inactive_date":
			out.Values[i] = ec._Project_inactive_date(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "minimum_time":
			out.Values[i] = ec._Project_minimum_time(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "minimum_altitude":
			out.Values[i] = ec._Project_minimum_altitude(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "use_custom_horizon":
			out.Values[i] = ec._Project_use_custom_horizon(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "horizon_offset":
			out.Values[i] = ec._Project_horizon_offset(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "meridian_window":
			out.Values[i] = ec._Project_meridian_window(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "filter_switch_frequency":
			out.Values[i] = ec._Project_filter_switch_frequency(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "dither_every":
			out.Values[i] = ec._Project_dither_every(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "enable_grader":
			out.Values[i] = ec._Project_enable_grader(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "is_mosaic":
			out.Values[i] = ec._Project_is_mosaic(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "flats_handling":
			out.Values[i] = ec._Project_flats_handling(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "maximum_altitude":
			out.Values[i] = ec._Project_maximum_altitude(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "smart_exposure_order":
			out.Values[i] = ec._Project_smart_exposure_order(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				atomic.AddUint32(&out.Invalids, 1)
			}
		case "targets":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Project_targets(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "stats":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Project_stats(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "mosaics":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Project_mosaics(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "cover":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Project_cover(ctx, field, obj)
				if res == graphql.RequiredNull {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferLabelToView), math.MaxInt32)))

	ec.ProcessDeferredGroup(graphql.DeferredGroup{
		Defers:   deferLabelToView,
		Path:     graphql.GetPath(ctx),
		FieldSet: deferredFieldSet,
		Context:  ctx,
	})

	return out
}

var projectCoverImplementors = []string{"ProjectCover"}

func (ec *executionContext) _ProjectCover(ctx context.Context, sel ast.SelectionSet, obj *model.ProjectCover) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, projectCoverImplementors)

	out := graphql.NewFieldSet(fields)
	deferredFieldSet := graphql.NewFieldSet(nil)
	deferLabelToView := make(map[string]*graphql.FieldSetView)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("ProjectCover")
		case "palette":
			out.Values[i] = ec._ProjectCover_palette(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "filter":
			out.Values[i] = ec._ProjectCover_filter(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "preview_url":
			out.Values[i] = ec._ProjectCover_preview_url(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "mosaic":
			out.Values[i] = ec._ProjectCover_mosaic(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "updated_at":
			out.Values[i] = ec._ProjectCover_updated_at(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "panels":
			out.Values[i] = ec._ProjectCover_panels(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				out.Invalids++
			}
		case "panels_total":
			out.Values[i] = ec._ProjectCover_panels_total(ctx, field, obj)
			if out.Values[i] == graphql.RequiredNull {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferLabelToView), math.MaxInt32)))

	ec.ProcessDeferredGroup(graphql.DeferredGroup{
		Defers:   deferLabelToView,
		Path:     graphql.GetPath(ctx),
		FieldSet: deferredFieldSet,
		Context:  ctx,
	})

	return out
}

var projectStatsImplementors = []string{"ProjectStats"}

func (ec *executionContext) _ProjectStats(ctx context.Context, sel ast.SelectionSet, obj *model.ProjectStats) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, projectStatsImplementors)

	out := graphql.NewFieldSet(fields)
	deferredFieldSet := graphql.NewFieldSet(nil)
	deferLabelToView := make(map[string]*graphql.FieldSetView)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("ProjectStats")
		case "imaging":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._ProjectStats_imaging(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "last_image_date":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._ProjectStats_last_image_date(ctx, field, obj)
				if res == graphql.RequiredNull {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "plans":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._ProjectStats_plans(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		case "plans_met":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._ProjectStats_plans_met(ctx, field, obj)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			if field.IsDeferred() {
				deferredFieldSet.AddField(field)
				fieldIndex := len(deferredFieldSet.Values) - 1
				deferredFieldSet.Concurrently(fieldIndex, func(ctx context.Context) graphql.Marshaler {
					return innerFunc(ctx, deferredFieldSet)
				})

				for _, deferrable := range field.Deferrables {
					view, ok := deferLabelToView[deferrable.Label]
					if !ok {
						view = deferredFieldSet.NewView()
						deferLabelToView[deferrable.Label] = view
					}
					view.AddIndices(fieldIndex)
				}

				// don't run the out.Concurrently() call below
				out.Values[i] = graphql.Null
				continue
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(min(len(deferLabelToView), math.MaxInt32)))

	ec.ProcessDeferredGroup(graphql.DeferredGroup{
		Defers:   deferLabelToView,
		Path:     graphql.GetPath(ctx),
		FieldSet: deferredFieldSet,
		Context:  ctx,
	})

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) marshalNProject2ᚕᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectᚄ(ctx context.Context, sel ast.SelectionSet, v []*model.Project) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return ec.marshalNProject2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProject(ctx, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

func (ec *executionContext) marshalNProject2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProject(ctx context.Context, sel ast.SelectionSet, v *model.Project) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._Project(ctx, sel, v)
}

func (ec *executionContext) unmarshalNProjectOrderField2githubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectOrderField(ctx context.Context, v any) (model.ProjectOrderField, error) {
	var res model.ProjectOrderField
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNProjectOrderField2githubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectOrderField(ctx context.Context, sel ast.SelectionSet, v model.ProjectOrderField) graphql.Marshaler {
	return v
}

func (ec *executionContext) marshalNProjectStats2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectStats(ctx context.Context, sel ast.SelectionSet, v *model.ProjectStats) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._ProjectStats(ctx, sel, v)
}

func (ec *executionContext) marshalOProject2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProject(ctx context.Context, sel ast.SelectionSet, v *model.Project) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	return ec._Project(ctx, sel, v)
}

func (ec *executionContext) marshalOProjectCover2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectCover(ctx context.Context, sel ast.SelectionSet, v *model.ProjectCover) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	return ec._ProjectCover(ctx, sel, v)
}

func (ec *executionContext) unmarshalOProjectOrderBy2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectOrderBy(ctx context.Context, v any) (*model.ProjectOrderBy, error) {
	if v == nil {
		return nil, nil
	}
	res, err := ec.unmarshalInputProjectOrderBy(ctx, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) unmarshalOProjectPriority2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectPriority(ctx context.Context, v any) (*model.ProjectPriority, error) {
	if v == nil {
		return nil, nil
	}
	var res = new(model.ProjectPriority)
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalOProjectPriority2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectPriority(ctx context.Context, sel ast.SelectionSet, v *model.ProjectPriority) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	return v
}

func (ec *executionContext) unmarshalOProjectState2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectState(ctx context.Context, v any) (*model.ProjectState, error) {
	if v == nil {
		return nil, nil
	}
	var res = new(model.ProjectState)
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalOProjectState2ᚖgithubᚗcomᚋUSAᚑRedDragonᚋastroᚑprocessingᚋinternalᚋserverᚋgraphᚋmodelᚐProjectState(ctx context.Context, sel ast.SelectionSet, v *model.ProjectState) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	return v
}

// endregion ***************************** type.gotpl *****************************
