// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"context"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	OtherTarget() OtherTargetResolver
	Project() ProjectResolver
	ProjectStats() ProjectStatsResolver
	Query() QueryResolver
	Target() TargetResolver
	TargetStats() TargetStatsResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	CalibrationBasis struct {
		BinX     func(childComplexity int) int
		Exposure func(childComplexity int) int
		Gain     func(childComplexity int) int
		Night    func(childComplexity int) int
		Offset   func(childComplexity int) int
		SetTemp  func(childComplexity int) int
	}

	CalibrationMatch struct {
		AgeDays          func(childComplexity int) int
		Basis            func(childComplexity int) int
		Exposure         func(childComplexity int) int
		Frames           func(childComplexity int) int
		HeaderError      func(childComplexity int) int
		Master           func(childComplexity int) int
		Night            func(childComplexity int) int
		Quality          func(childComplexity int) int
		RotationMismatch func(childComplexity int) int
		Scaled           func(childComplexity int) int
		SetTemp          func(childComplexity int) int
		Source           func(childComplexity int) int
		TempOff          func(childComplexity int) int
	}

	CalibrationRow struct {
		Bias     func(childComplexity int) int
		Dark     func(childComplexity int) int
		Exposure func(childComplexity int) int
		Filter   func(childComplexity int) int
		Flat     func(childComplexity int) int
		Gain     func(childComplexity int) int
		Lights   func(childComplexity int) int
		Night    func(childComplexity int) int
		Offset   func(childComplexity int) int
		Rotator  func(childComplexity int) int
		SetTemp  func(childComplexity int) int
	}

	Crop struct {
		H func(childComplexity int) int
		W func(childComplexity int) int
		X func(childComplexity int) int
		Y func(childComplexity int) int
	}

	DarkLibrary struct {
		Gaps             func(childComplexity int) int
		Ladder           func(childComplexity int) int
		MinFrames        func(childComplexity int) int
		SetTempExactC    func(childComplexity int) int
		SetTempScaleMaxC func(childComplexity int) int
	}

	DarkLibraryGap struct {
		Exposure       func(childComplexity int) int
		Gain           func(childComplexity int) int
		LatestNight    func(childComplexity int) int
		Lights         func(childComplexity int) int
		Nights         func(childComplexity int) int
		Offset         func(childComplexity int) int
		OtherExposures func(childComplexity int) int
		SetTemp        func(childComplexity int) int
	}

	FilterMaster struct {
		CometPreviewURL func(childComplexity int) int
		CometURL        func(childComplexity int) int
		CometXisfURL    func(childComplexity int) int
		Crop            func(childComplexity int) int
		EffectiveHours  func(childComplexity int) int
		ExposureHours   func(childComplexity int) int
		Filter          func(childComplexity int) int
		FitReference    func(childComplexity int) int
		FittedURL       func(childComplexity int) int
		Height          func(childComplexity int) int
		LinearURL       func(childComplexity int) int
		LowestScore     func(childComplexity int) int
		MasterURL       func(childComplexity int) int
		MinScore        func(childComplexity int) int
		ObjectLights    func(childComplexity int) int
		PreviewURL      func(childComplexity int) int
		Subs            func(childComplexity int) int
		TargetSubs      func(childComplexity int) int
		UpdatedAt       func(childComplexity int) int
		Width           func(childComplexity int) int
		XisfURL         func(childComplexity int) int
	}

	FilterQuality struct {
		BelowCut            func(childComplexity int) int
		Cut                 func(childComplexity int) int
		EffectiveHours      func(childComplexity int) int
		ExposureTime        func(childComplexity int) int
		FilterName          func(childComplexity int) int
		MedianHfr           func(childComplexity int) int
		MedianSky           func(childComplexity int) int
		MinScore            func(childComplexity int) int
		NominalHours        func(childComplexity int) int
		Pending             func(childComplexity int) int
		ReferencePercentile func(childComplexity int) int
		ReferenceSubs       func(childComplexity int) int
		ReferenceWeight     func(childComplexity int) int
		RejectedInScheduler func(childComplexity int) int
		SkyBasis            func(childComplexity int) int
		Stacked             func(childComplexity int) int
		Subframes           func(childComplexity int) int
		TargetBest          func(childComplexity int) int
		Unmeasured          func(childComplexity int) int
	}

	ImagingStats struct {
		AcceptedImages func(childComplexity int) int
		AcquiredImages func(childComplexity int) int
		DesiredImages  func(childComplexity int) int
		RejectedImages func(childComplexity int) int
	}

	Mosaic struct {
		Crop        func(childComplexity int) int
		Filter      func(childComplexity int) int
		Height      func(childComplexity int) int
		LinearURL   func(childComplexity int) int
		MasterURL   func(childComplexity int) int
		Panels      func(childComplexity int) int
		PanelsTotal func(childComplexity int) int
		PreviewURL  func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
		Width       func(childComplexity int) int
	}

	OtherTarget struct {
		Cover      func(childComplexity int) int
		FirstNight func(childComplexity int) int
		LastNight  func(childComplexity int) int
		Lights     func(childComplexity int) int
		Masters    func(childComplexity int) int
		Name       func(childComplexity int) int
		Nights     func(childComplexity int) int
		Recorded   func(childComplexity int) int
		Stacked    func(childComplexity int) int
	}

	Project struct {
		ActiveDate            func(childComplexity int) int
		Cover                 func(childComplexity int) int
		CreateDate            func(childComplexity int) int
		Description           func(childComplexity int) int
		DitherEvery           func(childComplexity int) int
		EnableGrader          func(childComplexity int) int
		FilterSwitchFrequency func(childComplexity int) int
		FlatsHandling         func(childComplexity int) int
		HorizonOffset         func(childComplexity int) int
		ID                    func(childComplexity int) int
		InactiveDate          func(childComplexity int) int
		IsMosaic              func(childComplexity int) int
		MaximumAltitude       func(childComplexity int) int
		MeridianWindow        func(childComplexity int) int
		MinimumAltitude       func(childComplexity int) int
		MinimumTime           func(childComplexity int) int
		Mosaics               func(childComplexity int) int
		Name                  func(childComplexity int) int
		Priority              func(childComplexity int) int
		ProfileID             func(childComplexity int) int
		SmartExposureOrder    func(childComplexity int) int
		State                 func(childComplexity int) int
		Stats                 func(childComplexity int) int
		Targets               func(childComplexity int) int
		UseCustomHorizon      func(childComplexity int) int
	}

	ProjectCover struct {
		Filter      func(childComplexity int) int
		Mosaic      func(childComplexity int) int
		Palette     func(childComplexity int) int
		Panels      func(childComplexity int) int
		PanelsTotal func(childComplexity int) int
		PreviewURL  func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	ProjectStats struct {
		Imaging       func(childComplexity int) int
		LastImageDate func(childComplexity int) int
		Plans         func(childComplexity int) int
		PlansMet      func(childComplexity int) int
	}

	Query struct {
		Commit       func(childComplexity int) int
		DarkLibrary  func(childComplexity int) int
		OtherTarget  func(childComplexity int, name string) int
		OtherTargets func(childComplexity int) int
		Project      func(childComplexity int, id int) int
		Projects     func(childComplexity int, orderBy *model.ProjectOrderBy) int
		Target       func(childComplexity int, id int) int
		Targets      func(childComplexity int, orderBy *model.TargetOrderBy) int
		Version      func(childComplexity int) int
	}

	Subframe struct {
		AcquiredDate        func(childComplexity int) int
		Airmass             func(childComplexity int) int
		Cut                 func(childComplexity int) int
		Eccentricity        func(childComplexity int) int
		ExposureTime        func(childComplexity int) int
		FileName            func(childComplexity int) int
		FilterName          func(childComplexity int) int
		Fwhm                func(childComplexity int) int
		GradingStatus       func(childComplexity int) int
		GuidingRmsArcsec    func(childComplexity int) int
		Hfr                 func(childComplexity int) int
		ID                  func(childComplexity int) int
		PedestalAdu         func(childComplexity int) int
		PedestalBasis       func(childComplexity int) int
		PedestalSource      func(childComplexity int) int
		Photometry          func(childComplexity int) int
		PreviewURL          func(childComplexity int) int
		RejectReason        func(childComplexity int) int
		Score               func(childComplexity int) int
		ScoreMissing        func(childComplexity int) int
		Sky                 func(childComplexity int) int
		SkyMissing          func(childComplexity int) int
		StackReason         func(childComplexity int) int
		StackStatus         func(childComplexity int) int
		Stars               func(childComplexity int) int
		TargetBest          func(childComplexity int) int
		Transparency        func(childComplexity int) int
		TransparencyMissing func(childComplexity int) int
		TransparencySource  func(childComplexity int) int
		Weight              func(childComplexity int) int
	}

	Target struct {
		Active           func(childComplexity int) int
		Calibration      func(childComplexity int) int
		Dec              func(childComplexity int) int
		Epoch            func(childComplexity int) int
		ID               func(childComplexity int) int
		Masters          func(childComplexity int) int
		Name             func(childComplexity int) int
		Project          func(childComplexity int) int
		Ra               func(childComplexity int) int
		RegionOfInterest func(childComplexity int) int
		Rotation         func(childComplexity int) int
		Stats            func(childComplexity int) int
		Subframes        func(childComplexity int) int
	}

	TargetFilterStats struct {
		Enabled        func(childComplexity int) int
		Exposure       func(childComplexity int) int
		ExposureSource func(childComplexity int) int
		FilterName     func(childComplexity int) int
		Gain           func(childComplexity int) int
		Imaging        func(childComplexity int) int
		Offset         func(childComplexity int) int
		TemplateName   func(childComplexity int) int
	}

	TargetStats struct {
		Filters       func(childComplexity int) int
		LastImageDate func(childComplexity int) int
		Quality       func(childComplexity int) int
		Total         func(childComplexity int) int
	}
}

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "CalibrationBasis.bin_x":
		if e.ComplexityRoot.CalibrationBasis.BinX == nil {
			break
		}

		return e.ComplexityRoot.CalibrationBasis.BinX(childComplexity), true
	case "CalibrationBasis.exposure":
		if e.ComplexityRoot.CalibrationBasis.Exposure == nil {
			break
		}

		return e.ComplexityRoot.CalibrationBasis.Exposure(childComplexity), true
	case "CalibrationBasis.gain":
		if e.ComplexityRoot.CalibrationBasis.Gain == nil {
			break
		}

		return e.ComplexityRoot.CalibrationBasis.Gain(childComplexity), true
	case "CalibrationBasis.night":
		if e.ComplexityRoot.CalibrationBasis.Night == nil {
			break
		}

		return e.ComplexityRoot.CalibrationBasis.Night(childComplexity), true
	case "CalibrationBasis.offset":
		if e.ComplexityRoot.CalibrationBasis.Offset == nil {
			break
		}

		return e.ComplexityRoot.CalibrationBasis.Offset(childComplexity), true
	case "CalibrationBasis.set_temp":
		if e.ComplexityRoot.CalibrationBasis.SetTemp == nil {
			break
		}

		return e.ComplexityRoot.CalibrationBasis.SetTemp(childComplexity), true

	case "CalibrationMatch.age_days":
		if e.ComplexityRoot.CalibrationMatch.AgeDays == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.AgeDays(childComplexity), true
	case "CalibrationMatch.basis":
		if e.ComplexityRoot.CalibrationMatch.Basis == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Basis(childComplexity), true
	case "CalibrationMatch.exposure":
		if e.ComplexityRoot.CalibrationMatch.Exposure == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Exposure(childComplexity), true
	case "CalibrationMatch.frames":
		if e.ComplexityRoot.CalibrationMatch.Frames == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Frames(childComplexity), true
	case "CalibrationMatch.header_error":
		if e.ComplexityRoot.CalibrationMatch.HeaderError == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.HeaderError(childComplexity), true
	case "CalibrationMatch.master":
		if e.ComplexityRoot.CalibrationMatch.Master == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Master(childComplexity), true
	case "CalibrationMatch.night":
		if e.ComplexityRoot.CalibrationMatch.Night == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Night(childComplexity), true
	case "CalibrationMatch.quality":
		if e.ComplexityRoot.CalibrationMatch.Quality == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Quality(childComplexity), true
	case "CalibrationMatch.rotation_mismatch":
		if e.ComplexityRoot.CalibrationMatch.RotationMismatch == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.RotationMismatch(childComplexity), true
	case "CalibrationMatch.scaled":
		if e.ComplexityRoot.CalibrationMatch.Scaled == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Scaled(childComplexity), true
	case "CalibrationMatch.set_temp":
		if e.ComplexityRoot.CalibrationMatch.SetTemp == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.SetTemp(childComplexity), true
	case "CalibrationMatch.source":
		if e.ComplexityRoot.CalibrationMatch.Source == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.Source(childComplexity), true
	case "CalibrationMatch.temp_off":
		if e.ComplexityRoot.CalibrationMatch.TempOff == nil {
			break
		}

		return e.ComplexityRoot.CalibrationMatch.TempOff(childComplexity), true

	case "CalibrationRow.bias":
		if e.ComplexityRoot.CalibrationRow.Bias == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Bias(childComplexity), true
	case "CalibrationRow.dark":
		if e.ComplexityRoot.CalibrationRow.Dark == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Dark(childComplexity), true
	case "CalibrationRow.exposure":
		if e.ComplexityRoot.CalibrationRow.Exposure == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Exposure(childComplexity), true
	case "CalibrationRow.filter":
		if e.ComplexityRoot.CalibrationRow.Filter == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Filter(childComplexity), true
	case "CalibrationRow.flat":
		if e.ComplexityRoot.CalibrationRow.Flat == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Flat(childComplexity), true
	case "CalibrationRow.gain":
		if e.ComplexityRoot.CalibrationRow.Gain == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Gain(childComplexity), true
	case "CalibrationRow.lights":
		if e.ComplexityRoot.CalibrationRow.Lights == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Lights(childComplexity), true
	case "CalibrationRow.night":
		if e.ComplexityRoot.CalibrationRow.Night == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Night(childComplexity), true
	case "CalibrationRow.offset":
		if e.ComplexityRoot.CalibrationRow.Offset == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Offset(childComplexity), true
	case "CalibrationRow.rotator":
		if e.ComplexityRoot.CalibrationRow.Rotator == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.Rotator(childComplexity), true
	case "CalibrationRow.set_temp":
		if e.ComplexityRoot.CalibrationRow.SetTemp == nil {
			break
		}

		return e.ComplexityRoot.CalibrationRow.SetTemp(childComplexity), true

	case "Crop.h":
		if e.ComplexityRoot.Crop.H == nil {
			break
		}

		return e.ComplexityRoot.Crop.H(childComplexity), true
	case "Crop.w":
		if e.ComplexityRoot.Crop.W == nil {
			break
		}

		return e.ComplexityRoot.Crop.W(childComplexity), true
	case "Crop.x":
		if e.ComplexityRoot.Crop.X == nil {
			break
		}

		return e.ComplexityRoot.Crop.X(childComplexity), true
	case "Crop.y":
		if e.ComplexityRoot.Crop.Y == nil {
			break
		}

		return e.ComplexityRoot.Crop.Y(childComplexity), true

	case "DarkLibrary.gaps":
		if e.ComplexityRoot.DarkLibrary.Gaps == nil {
			break
		}

		return e.ComplexityRoot.DarkLibrary.Gaps(childComplexity), true
	case "DarkLibrary.ladder":
		if e.ComplexityRoot.DarkLibrary.Ladder == nil {
			break
		}

		return e.ComplexityRoot.DarkLibrary.Ladder(childComplexity), true
	case "DarkLibrary.min_frames":
		if e.ComplexityRoot.DarkLibrary.MinFrames == nil {
			break
		}

		return e.ComplexityRoot.DarkLibrary.MinFrames(childComplexity), true
	case "DarkLibrary.set_temp_exact_c":
		if e.ComplexityRoot.DarkLibrary.SetTempExactC == nil {
			break
		}

		return e.ComplexityRoot.DarkLibrary.SetTempExactC(childComplexity), true
	case "DarkLibrary.set_temp_scale_max_c":
		if e.ComplexityRoot.DarkLibrary.SetTempScaleMaxC == nil {
			break
		}

		return e.ComplexityRoot.DarkLibrary.SetTempScaleMaxC(childComplexity), true

	case "DarkLibraryGap.exposure":
		if e.ComplexityRoot.DarkLibraryGap.Exposure == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.Exposure(childComplexity), true
	case "DarkLibraryGap.gain":
		if e.ComplexityRoot.DarkLibraryGap.Gain == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.Gain(childComplexity), true
	case "DarkLibraryGap.latest_night":
		if e.ComplexityRoot.DarkLibraryGap.LatestNight == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.LatestNight(childComplexity), true
	case "DarkLibraryGap.lights":
		if e.ComplexityRoot.DarkLibraryGap.Lights == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.Lights(childComplexity), true
	case "DarkLibraryGap.nights":
		if e.ComplexityRoot.DarkLibraryGap.Nights == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.Nights(childComplexity), true
	case "DarkLibraryGap.offset":
		if e.ComplexityRoot.DarkLibraryGap.Offset == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.Offset(childComplexity), true
	case "DarkLibraryGap.other_exposures":
		if e.ComplexityRoot.DarkLibraryGap.OtherExposures == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.OtherExposures(childComplexity), true
	case "DarkLibraryGap.set_temp":
		if e.ComplexityRoot.DarkLibraryGap.SetTemp == nil {
			break
		}

		return e.ComplexityRoot.DarkLibraryGap.SetTemp(childComplexity), true

	case "FilterMaster.comet_preview_url":
		if e.ComplexityRoot.FilterMaster.CometPreviewURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.CometPreviewURL(childComplexity), true
	case "FilterMaster.comet_url":
		if e.ComplexityRoot.FilterMaster.CometURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.CometURL(childComplexity), true
	case "FilterMaster.comet_xisf_url":
		if e.ComplexityRoot.FilterMaster.CometXisfURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.CometXisfURL(childComplexity), true
	case "FilterMaster.crop":
		if e.ComplexityRoot.FilterMaster.Crop == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.Crop(childComplexity), true
	case "FilterMaster.effective_hours":
		if e.ComplexityRoot.FilterMaster.EffectiveHours == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.EffectiveHours(childComplexity), true
	case "FilterMaster.exposure_hours":
		if e.ComplexityRoot.FilterMaster.ExposureHours == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.ExposureHours(childComplexity), true
	case "FilterMaster.filter":
		if e.ComplexityRoot.FilterMaster.Filter == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.Filter(childComplexity), true
	case "FilterMaster.fit_reference":
		if e.ComplexityRoot.FilterMaster.FitReference == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.FitReference(childComplexity), true
	case "FilterMaster.fitted_url":
		if e.ComplexityRoot.FilterMaster.FittedURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.FittedURL(childComplexity), true
	case "FilterMaster.height":
		if e.ComplexityRoot.FilterMaster.Height == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.Height(childComplexity), true
	case "FilterMaster.linear_url":
		if e.ComplexityRoot.FilterMaster.LinearURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.LinearURL(childComplexity), true
	case "FilterMaster.lowest_score":
		if e.ComplexityRoot.FilterMaster.LowestScore == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.LowestScore(childComplexity), true
	case "FilterMaster.master_url":
		if e.ComplexityRoot.FilterMaster.MasterURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.MasterURL(childComplexity), true
	case "FilterMaster.min_score":
		if e.ComplexityRoot.FilterMaster.MinScore == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.MinScore(childComplexity), true
	case "FilterMaster.object_lights":
		if e.ComplexityRoot.FilterMaster.ObjectLights == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.ObjectLights(childComplexity), true
	case "FilterMaster.preview_url":
		if e.ComplexityRoot.FilterMaster.PreviewURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.PreviewURL(childComplexity), true
	case "FilterMaster.subs":
		if e.ComplexityRoot.FilterMaster.Subs == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.Subs(childComplexity), true
	case "FilterMaster.target_subs":
		if e.ComplexityRoot.FilterMaster.TargetSubs == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.TargetSubs(childComplexity), true
	case "FilterMaster.updated_at":
		if e.ComplexityRoot.FilterMaster.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.UpdatedAt(childComplexity), true
	case "FilterMaster.width":
		if e.ComplexityRoot.FilterMaster.Width == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.Width(childComplexity), true
	case "FilterMaster.xisf_url":
		if e.ComplexityRoot.FilterMaster.XisfURL == nil {
			break
		}

		return e.ComplexityRoot.FilterMaster.XisfURL(childComplexity), true

	case "FilterQuality.below_cut":
		if e.ComplexityRoot.FilterQuality.BelowCut == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.BelowCut(childComplexity), true
	case "FilterQuality.cut":
		if e.ComplexityRoot.FilterQuality.Cut == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.Cut(childComplexity), true
	case "FilterQuality.effective_hours":
		if e.ComplexityRoot.FilterQuality.EffectiveHours == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.EffectiveHours(childComplexity), true
	case "FilterQuality.exposure_time":
		if e.ComplexityRoot.FilterQuality.ExposureTime == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.ExposureTime(childComplexity), true
	case "FilterQuality.filter_name":
		if e.ComplexityRoot.FilterQuality.FilterName == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.FilterName(childComplexity), true
	case "FilterQuality.median_hfr":
		if e.ComplexityRoot.FilterQuality.MedianHfr == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.MedianHfr(childComplexity), true
	case "FilterQuality.median_sky":
		if e.ComplexityRoot.FilterQuality.MedianSky == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.MedianSky(childComplexity), true
	case "FilterQuality.min_score":
		if e.ComplexityRoot.FilterQuality.MinScore == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.MinScore(childComplexity), true
	case "FilterQuality.nominal_hours":
		if e.ComplexityRoot.FilterQuality.NominalHours == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.NominalHours(childComplexity), true
	case "FilterQuality.pending":
		if e.ComplexityRoot.FilterQuality.Pending == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.Pending(childComplexity), true
	case "FilterQuality.reference_percentile":
		if e.ComplexityRoot.FilterQuality.ReferencePercentile == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.ReferencePercentile(childComplexity), true
	case "FilterQuality.reference_subs":
		if e.ComplexityRoot.FilterQuality.ReferenceSubs == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.ReferenceSubs(childComplexity), true
	case "FilterQuality.reference_weight":
		if e.ComplexityRoot.FilterQuality.ReferenceWeight == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.ReferenceWeight(childComplexity), true
	case "FilterQuality.rejected_in_scheduler":
		if e.ComplexityRoot.FilterQuality.RejectedInScheduler == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.RejectedInScheduler(childComplexity), true
	case "FilterQuality.sky_basis":
		if e.ComplexityRoot.FilterQuality.SkyBasis == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.SkyBasis(childComplexity), true
	case "FilterQuality.stacked":
		if e.ComplexityRoot.FilterQuality.Stacked == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.Stacked(childComplexity), true
	case "FilterQuality.subframes":
		if e.ComplexityRoot.FilterQuality.Subframes == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.Subframes(childComplexity), true
	case "FilterQuality.target_best":
		if e.ComplexityRoot.FilterQuality.TargetBest == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.TargetBest(childComplexity), true
	case "FilterQuality.unmeasured":
		if e.ComplexityRoot.FilterQuality.Unmeasured == nil {
			break
		}

		return e.ComplexityRoot.FilterQuality.Unmeasured(childComplexity), true

	case "ImagingStats.accepted_images":
		if e.ComplexityRoot.ImagingStats.AcceptedImages == nil {
			break
		}

		return e.ComplexityRoot.ImagingStats.AcceptedImages(childComplexity), true
	case "ImagingStats.acquired_images":
		if e.ComplexityRoot.ImagingStats.AcquiredImages == nil {
			break
		}

		return e.ComplexityRoot.ImagingStats.AcquiredImages(childComplexity), true
	case "ImagingStats.desired_images":
		if e.ComplexityRoot.ImagingStats.DesiredImages == nil {
			break
		}

		return e.ComplexityRoot.ImagingStats.DesiredImages(childComplexity), true
	case "ImagingStats.rejected_images":
		if e.ComplexityRoot.ImagingStats.RejectedImages == nil {
			break
		}

		return e.ComplexityRoot.ImagingStats.RejectedImages(childComplexity), true

	case "Mosaic.crop":
		if e.ComplexityRoot.Mosaic.Crop == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.Crop(childComplexity), true
	case "Mosaic.filter":
		if e.ComplexityRoot.Mosaic.Filter == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.Filter(childComplexity), true
	case "Mosaic.height":
		if e.ComplexityRoot.Mosaic.Height == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.Height(childComplexity), true
	case "Mosaic.linear_url":
		if e.ComplexityRoot.Mosaic.LinearURL == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.LinearURL(childComplexity), true
	case "Mosaic.master_url":
		if e.ComplexityRoot.Mosaic.MasterURL == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.MasterURL(childComplexity), true
	case "Mosaic.panels":
		if e.ComplexityRoot.Mosaic.Panels == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.Panels(childComplexity), true
	case "Mosaic.panels_total":
		if e.ComplexityRoot.Mosaic.PanelsTotal == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.PanelsTotal(childComplexity), true
	case "Mosaic.preview_url":
		if e.ComplexityRoot.Mosaic.PreviewURL == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.PreviewURL(childComplexity), true
	case "Mosaic.updated_at":
		if e.ComplexityRoot.Mosaic.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.UpdatedAt(childComplexity), true
	case "Mosaic.width":
		if e.ComplexityRoot.Mosaic.Width == nil {
			break
		}

		return e.ComplexityRoot.Mosaic.Width(childComplexity), true

	case "OtherTarget.cover":
		if e.ComplexityRoot.OtherTarget.Cover == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Cover(childComplexity), true
	case "OtherTarget.first_night":
		if e.ComplexityRoot.OtherTarget.FirstNight == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.FirstNight(childComplexity), true
	case "OtherTarget.last_night":
		if e.ComplexityRoot.OtherTarget.LastNight == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.LastNight(childComplexity), true
	case "OtherTarget.lights":
		if e.ComplexityRoot.OtherTarget.Lights == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Lights(childComplexity), true
	case "OtherTarget.masters":
		if e.ComplexityRoot.OtherTarget.Masters == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Masters(childComplexity), true
	case "OtherTarget.name":
		if e.ComplexityRoot.OtherTarget.Name == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Name(childComplexity), true
	case "OtherTarget.nights":
		if e.ComplexityRoot.OtherTarget.Nights == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Nights(childComplexity), true
	case "OtherTarget.recorded":
		if e.ComplexityRoot.OtherTarget.Recorded == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Recorded(childComplexity), true
	case "OtherTarget.stacked":
		if e.ComplexityRoot.OtherTarget.Stacked == nil {
			break
		}

		return e.ComplexityRoot.OtherTarget.Stacked(childComplexity), true

	case "Project.active_date":
		if e.ComplexityRoot.Project.ActiveDate == nil {
			break
		}

		return e.ComplexityRoot.Project.ActiveDate(childComplexity), true
	case "Project.cover":
		if e.ComplexityRoot.Project.Cover == nil {
			break
		}

		return e.ComplexityRoot.Project.Cover(childComplexity), true
	case "Project.create_date":
		if e.ComplexityRoot.Project.CreateDate == nil {
			break
		}

		return e.ComplexityRoot.Project.CreateDate(childComplexity), true
	case "Project.description":
		if e.ComplexityRoot.Project.Description == nil {
			break
		}

		return e.ComplexityRoot.Project.Description(childComplexity), true
	case "Project.dither_every":
		if e.ComplexityRoot.Project.DitherEvery == nil {
			break
		}

		return e.ComplexityRoot.Project.DitherEvery(childComplexity), true
	case "Project.enable_grader":
		if e.ComplexityRoot.Project.EnableGrader == nil {
			break
		}

		return e.ComplexityRoot.Project.EnableGrader(childComplexity), true
	case "Project.filter_switch_frequency":
		if e.ComplexityRoot.Project.FilterSwitchFrequency == nil {
			break
		}

		return e.ComplexityRoot.Project.FilterSwitchFrequency(childComplexity), true
	case "Project.flats_handling":
		if e.ComplexityRoot.Project.FlatsHandling == nil {
			break
		}

		return e.ComplexityRoot.Project.FlatsHandling(childComplexity), true
	case "Project.horizon_offset":
		if e.ComplexityRoot.Project.HorizonOffset == nil {
			break
		}

		return e.ComplexityRoot.Project.HorizonOffset(childComplexity), true
	case "Project.id":
		if e.ComplexityRoot.Project.ID == nil {
			break
		}

		return e.ComplexityRoot.Project.ID(childComplexity), true
	case "Project.inactive_date":
		if e.ComplexityRoot.Project.InactiveDate == nil {
			break
		}

		return e.ComplexityRoot.Project.InactiveDate(childComplexity), true
	case "Project.is_mosaic":
		if e.ComplexityRoot.Project.IsMosaic == nil {
			break
		}

		return e.ComplexityRoot.Project.IsMosaic(childComplexity), true
	case "Project.maximum_altitude":
		if e.ComplexityRoot.Project.MaximumAltitude == nil {
			break
		}

		return e.ComplexityRoot.Project.MaximumAltitude(childComplexity), true
	case "Project.meridian_window":
		if e.ComplexityRoot.Project.MeridianWindow == nil {
			break
		}

		return e.ComplexityRoot.Project.MeridianWindow(childComplexity), true
	case "Project.minimum_altitude":
		if e.ComplexityRoot.Project.MinimumAltitude == nil {
			break
		}

		return e.ComplexityRoot.Project.MinimumAltitude(childComplexity), true
	case "Project.minimum_time":
		if e.ComplexityRoot.Project.MinimumTime == nil {
			break
		}

		return e.ComplexityRoot.Project.MinimumTime(childComplexity), true
	case "Project.mosaics":
		if e.ComplexityRoot.Project.Mosaics == nil {
			break
		}

		return e.ComplexityRoot.Project.Mosaics(childComplexity), true
	case "Project.name":
		if e.ComplexityRoot.Project.Name == nil {
			break
		}

		return e.ComplexityRoot.Project.Name(childComplexity), true
	case "Project.priority":
		if e.ComplexityRoot.Project.Priority == nil {
			break
		}

		return e.ComplexityRoot.Project.Priority(childComplexity), true
	case "Project.profile_id":
		if e.ComplexityRoot.Project.ProfileID == nil {
			break
		}

		return e.ComplexityRoot.Project.ProfileID(childComplexity), true
	case "Project.smart_exposure_order":
		if e.ComplexityRoot.Project.SmartExposureOrder == nil {
			break
		}

		return e.ComplexityRoot.Project.SmartExposureOrder(childComplexity), true
	case "Project.state":
		if e.ComplexityRoot.Project.State == nil {
			break
		}

		return e.ComplexityRoot.Project.State(childComplexity), true
	case "Project.stats":
		if e.ComplexityRoot.Project.Stats == nil {
			break
		}

		return e.ComplexityRoot.Project.Stats(childComplexity), true
	case "Project.targets":
		if e.ComplexityRoot.Project.Targets == nil {
			break
		}

		return e.ComplexityRoot.Project.Targets(childComplexity), true
	case "Project.use_custom_horizon":
		if e.ComplexityRoot.Project.UseCustomHorizon == nil {
			break
		}

		return e.ComplexityRoot.Project.UseCustomHorizon(childComplexity), true

	case "ProjectCover.filter":
		if e.ComplexityRoot.ProjectCover.Filter == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.Filter(childComplexity), true
	case "ProjectCover.mosaic":
		if e.ComplexityRoot.ProjectCover.Mosaic == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.Mosaic(childComplexity), true
	case "ProjectCover.palette":
		if e.ComplexityRoot.ProjectCover.Palette == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.Palette(childComplexity), true
	case "ProjectCover.panels":
		if e.ComplexityRoot.ProjectCover.Panels == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.Panels(childComplexity), true
	case "ProjectCover.panels_total":
		if e.ComplexityRoot.ProjectCover.PanelsTotal == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.PanelsTotal(childComplexity), true
	case "ProjectCover.preview_url":
		if e.ComplexityRoot.ProjectCover.PreviewURL == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.PreviewURL(childComplexity), true
	case "ProjectCover.updated_at":
		if e.ComplexityRoot.ProjectCover.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.ProjectCover.UpdatedAt(childComplexity), true

	case "ProjectStats.imaging":
		if e.ComplexityRoot.ProjectStats.Imaging == nil {
			break
		}

		return e.ComplexityRoot.ProjectStats.Imaging(childComplexity), true
	case "ProjectStats.last_image_date":
		if e.ComplexityRoot.ProjectStats.LastImageDate == nil {
			break
		}

		return e.ComplexityRoot.ProjectStats.LastImageDate(childComplexity), true
	case "ProjectStats.plans":
		if e.ComplexityRoot.ProjectStats.Plans == nil {
			break
		}

		return e.ComplexityRoot.ProjectStats.Plans(childComplexity), true
	case "ProjectStats.plans_met":
		if e.ComplexityRoot.ProjectStats.PlansMet == nil {
			break
		}

		return e.ComplexityRoot.ProjectStats.PlansMet(childComplexity), true

	case "Query.commit":
		if e.ComplexityRoot.Query.Commit == nil {
			break
		}

		return e.ComplexityRoot.Query.Commit(childComplexity), true
	case "Query.darkLibrary":
		if e.ComplexityRoot.Query.DarkLibrary == nil {
			break
		}

		return e.ComplexityRoot.Query.DarkLibrary(childComplexity), true

	case "Query.otherTarget":
		if e.ComplexityRoot.Query.OtherTarget == nil {
			break
		}

		args, err := ec.field_Query_otherTarget_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.OtherTarget(childComplexity, args["name"].(string)), true
	case "Query.otherTargets":
		if e.ComplexityRoot.Query.OtherTargets == nil {
			break
		}

		return e.ComplexityRoot.Query.OtherTargets(childComplexity), true
	case "Query.project":
		if e.ComplexityRoot.Query.Project == nil {
			break
		}

		args, err := ec.field_Query_project_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Project(childComplexity, args["id"].(int)), true
	case "Query.projects":
		if e.ComplexityRoot.Query.Projects == nil {
			break
		}

		args, err := ec.field_Query_projects_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Projects(childComplexity, args["orderBy"].(*model.ProjectOrderBy)), true
	case "Query.target":
		if e.ComplexityRoot.Query.Target == nil {
			break
		}

		args, err := ec.field_Query_target_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Target(childComplexity, args["id"].(int)), true
	case "Query.targets":
		if e.ComplexityRoot.Query.Targets == nil {
			break
		}

		args, err := ec.field_Query_targets_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Targets(childComplexity, args["orderBy"].(*model.TargetOrderBy)), true
	case "Query.version":
		if e.ComplexityRoot.Query.Version == nil {
			break
		}

		return e.ComplexityRoot.Query.Version(childComplexity), true

	case "Subframe.acquired_date":
		if e.ComplexityRoot.Subframe.AcquiredDate == nil {
			break
		}

		return e.ComplexityRoot.Subframe.AcquiredDate(childComplexity), true
	case "Subframe.airmass":
		if e.ComplexityRoot.Subframe.Airmass == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Airmass(childComplexity), true
	case "Subframe.cut":
		if e.ComplexityRoot.Subframe.Cut == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Cut(childComplexity), true
	case "Subframe.eccentricity":
		if e.ComplexityRoot.Subframe.Eccentricity == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Eccentricity(childComplexity), true
	case "Subframe.exposure_time":
		if e.ComplexityRoot.Subframe.ExposureTime == nil {
			break
		}

		return e.ComplexityRoot.Subframe.ExposureTime(childComplexity), true
	case "Subframe.file_name":
		if e.ComplexityRoot.Subframe.FileName == nil {
			break
		}

		return e.ComplexityRoot.Subframe.FileName(childComplexity), true
	case "Subframe.filter_name":
		if e.ComplexityRoot.Subframe.FilterName == nil {
			break
		}

		return e.ComplexityRoot.Subframe.FilterName(childComplexity), true
	case "Subframe.fwhm":
		if e.ComplexityRoot.Subframe.Fwhm == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Fwhm(childComplexity), true
	case "Subframe.grading_status":
		if e.ComplexityRoot.Subframe.GradingStatus == nil {
			break
		}

		return e.ComplexityRoot.Subframe.GradingStatus(childComplexity), true
	case "Subframe.guiding_rms_arcsec":
		if e.ComplexityRoot.Subframe.GuidingRmsArcsec == nil {
			break
		}

		return e.ComplexityRoot.Subframe.GuidingRmsArcsec(childComplexity), true
	case "Subframe.hfr":
		if e.ComplexityRoot.Subframe.Hfr == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Hfr(childComplexity), true
	case "Subframe.id":
		if e.ComplexityRoot.Subframe.ID == nil {
			break
		}

		return e.ComplexityRoot.Subframe.ID(childComplexity), true
	case "Subframe.pedestal_adu":
		if e.ComplexityRoot.Subframe.PedestalAdu == nil {
			break
		}

		return e.ComplexityRoot.Subframe.PedestalAdu(childComplexity), true
	case "Subframe.pedestal_basis":
		if e.ComplexityRoot.Subframe.PedestalBasis == nil {
			break
		}

		return e.ComplexityRoot.Subframe.PedestalBasis(childComplexity), true
	case "Subframe.pedestal_source":
		if e.ComplexityRoot.Subframe.PedestalSource == nil {
			break
		}

		return e.ComplexityRoot.Subframe.PedestalSource(childComplexity), true
	case "Subframe.photometry":
		if e.ComplexityRoot.Subframe.Photometry == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Photometry(childComplexity), true
	case "Subframe.preview_url":
		if e.ComplexityRoot.Subframe.PreviewURL == nil {
			break
		}

		return e.ComplexityRoot.Subframe.PreviewURL(childComplexity), true
	case "Subframe.reject_reason":
		if e.ComplexityRoot.Subframe.RejectReason == nil {
			break
		}

		return e.ComplexityRoot.Subframe.RejectReason(childComplexity), true
	case "Subframe.score":
		if e.ComplexityRoot.Subframe.Score == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Score(childComplexity), true
	case "Subframe.score_missing":
		if e.ComplexityRoot.Subframe.ScoreMissing == nil {
			break
		}

		return e.ComplexityRoot.Subframe.ScoreMissing(childComplexity), true
	case "Subframe.sky":
		if e.ComplexityRoot.Subframe.Sky == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Sky(childComplexity), true
	case "Subframe.sky_missing":
		if e.ComplexityRoot.Subframe.SkyMissing == nil {
			break
		}

		return e.ComplexityRoot.Subframe.SkyMissing(childComplexity), true
	case "Subframe.stack_reason":
		if e.ComplexityRoot.Subframe.StackReason == nil {
			break
		}

		return e.ComplexityRoot.Subframe.StackReason(childComplexity), true
	case "Subframe.stack_status":
		if e.ComplexityRoot.Subframe.StackStatus == nil {
			break
		}

		return e.ComplexityRoot.Subframe.StackStatus(childComplexity), true
	case "Subframe.stars":
		if e.ComplexityRoot.Subframe.Stars == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Stars(childComplexity), true
	case "Subframe.target_best":
		if e.ComplexityRoot.Subframe.TargetBest == nil {
			break
		}

		return e.ComplexityRoot.Subframe.TargetBest(childComplexity), true
	case "Subframe.transparency":
		if e.ComplexityRoot.Subframe.Transparency == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Transparency(childComplexity), true
	case "Subframe.transparency_missing":
		if e.ComplexityRoot.Subframe.TransparencyMissing == nil {
			break
		}

		return e.ComplexityRoot.Subframe.TransparencyMissing(childComplexity), true
	case "Subframe.transparency_source":
		if e.ComplexityRoot.Subframe.TransparencySource == nil {
			break
		}

		return e.ComplexityRoot.Subframe.TransparencySource(childComplexity), true
	case "Subframe.weight":
		if e.ComplexityRoot.Subframe.Weight == nil {
			break
		}

		return e.ComplexityRoot.Subframe.Weight(childComplexity), true

	case "Target.active":
		if e.ComplexityRoot.Target.Active == nil {
			break
		}

		return e.ComplexityRoot.Target.Active(childComplexity), true
	case "Target.calibration":
		if e.ComplexityRoot.Target.Calibration == nil {
			break
		}

		return e.ComplexityRoot.Target.Calibration(childComplexity), true
	case "Target.dec":
		if e.ComplexityRoot.Target.Dec == nil {
			break
		}

		return e.ComplexityRoot.Target.Dec(childComplexity), true
	case "Target.epoch":
		if e.ComplexityRoot.Target.Epoch == nil {
			break
		}

		return e.ComplexityRoot.Target.Epoch(childComplexity), true
	case "Target.id":
		if e.ComplexityRoot.Target.ID == nil {
			break
		}

		return e.ComplexityRoot.Target.ID(childComplexity), true
	case "Target.masters":
		if e.ComplexityRoot.Target.Masters == nil {
			break
		}

		return e.ComplexityRoot.Target.Masters(childComplexity), true
	case "Target.name":
		if e.ComplexityRoot.Target.Name == nil {
			break
		}

		return e.ComplexityRoot.Target.Name(childComplexity), true
	case "Target.project":
		if e.ComplexityRoot.Target.Project == nil {
			break
		}

		return e.ComplexityRoot.Target.Project(childComplexity), true
	case "Target.ra":
		if e.ComplexityRoot.Target.Ra == nil {
			break
		}

		return e.ComplexityRoot.Target.Ra(childComplexity), true
	case "Target.region_of_interest":
		if e.ComplexityRoot.Target.RegionOfInterest == nil {
			break
		}

		return e.ComplexityRoot.Target.RegionOfInterest(childComplexity), true
	case "Target.rotation":
		if e.ComplexityRoot.Target.Rotation == nil {
			break
		}

		return e.ComplexityRoot.Target.Rotation(childComplexity), true
	case "Target.stats":
		if e.ComplexityRoot.Target.Stats == nil {
			break
		}

		return e.ComplexityRoot.Target.Stats(childComplexity), true
	case "Target.subframes":
		if e.ComplexityRoot.Target.Subframes == nil {
			break
		}

		return e.ComplexityRoot.Target.Subframes(childComplexity), true

	case "TargetFilterStats.enabled":
		if e.ComplexityRoot.TargetFilterStats.Enabled == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.Enabled(childComplexity), true
	case "TargetFilterStats.exposure":
		if e.ComplexityRoot.TargetFilterStats.Exposure == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.Exposure(childComplexity), true
	case "TargetFilterStats.exposure_source":
		if e.ComplexityRoot.TargetFilterStats.ExposureSource == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.ExposureSource(childComplexity), true
	case "TargetFilterStats.filter_name":
		if e.ComplexityRoot.TargetFilterStats.FilterName == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.FilterName(childComplexity), true
	case "TargetFilterStats.gain":
		if e.ComplexityRoot.TargetFilterStats.Gain == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.Gain(childComplexity), true
	case "TargetFilterStats.imaging":
		if e.ComplexityRoot.TargetFilterStats.Imaging == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.Imaging(childComplexity), true
	case "TargetFilterStats.offset":
		if e.ComplexityRoot.TargetFilterStats.Offset == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.Offset(childComplexity), true
	case "TargetFilterStats.template_name":
		if e.ComplexityRoot.TargetFilterStats.TemplateName == nil {
			break
		}

		return e.ComplexityRoot.TargetFilterStats.TemplateName(childComplexity), true

	case "TargetStats.filters":
		if e.ComplexityRoot.TargetStats.Filters == nil {
			break
		}

		return e.ComplexityRoot.TargetStats.Filters(childComplexity), true
	case "TargetStats.last_image_date":
		if e.ComplexityRoot.TargetStats.LastImageDate == nil {
			break
		}

		return e.ComplexityRoot.TargetStats.LastImageDate(childComplexity), true
	case "TargetStats.quality":
		if e.ComplexityRoot.TargetStats.Quality == nil {
			break
		}

		return e.ComplexityRoot.TargetStats.Quality(childComplexity), true
	case "TargetStats.total":
		if e.ComplexityRoot.TargetStats.Total == nil {
			break
		}

		return e.ComplexityRoot.TargetStats.Total(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputProjectOrderBy,
		ec.unmarshalInputTargetOrderBy,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

var sources = []*ast.Source{
	{Name: "../../../graph/calibration.graphqls", Input: `extend type Query {
  "The stacker's dark library settings and the dark sets lights need but no darks cover. Null when the worker is not configured."
  darkLibrary: DarkLibrary
}

"Where a calibration set comes from: built here from its frames, or a master made elsewhere and imported."
enum CalibrationSource {
  FRAMES
  IMPORTED
}

"Where each value of an imported master's setup came from: header, file name, folder name or hand-entered."
type CalibrationBasis {
  night: String
  exposure: String
  gain: String
  offset: String
  set_temp: String
  bin_x: String
}

type DarkLibrary {
  "Configured setpoints, in °C, the stacker keeps the dark library at. Empty when the stacker does not report them."
  ladder: [Float!]!
  "Fewest frames the stacker builds a master from."
  min_frames: Int
  "A dark set counts at a setpoint when within this many °C."
  set_temp_exact_c: Float
  "Furthest, in °C, a dark's setpoint may be from the lights' when its thermal signal is scaled."
  set_temp_scale_max_c: Float
  gaps: [DarkLibraryGap!]!
}

enum CalibrationQuality {
  EXACT
  FALLBACK
  MISSING
}

type CalibrationMatch {
  quality: CalibrationQuality!
  "Night the calibration frames were taken."
  night: String
  frames: Int
  "Nights between the lights and the calibration."
  age_days: Int!
  "Dark setpoint difference in °C."
  temp_off: Float
  "Dark setpoint in °C."
  set_temp: Float
  "The flat was taken at another rotator angle."
  rotation_mismatch: Boolean!
  "The dark's thermal signal must be scaled to the lights."
  scaled: Boolean!
  "Dark exposure in seconds."
  exposure: Float
  source: CalibrationSource
  "Object key of an imported master."
  master: String
  basis: CalibrationBasis
  "Why an imported master's header gave no values."
  header_error: String
}

"One night of lights sharing a filter and camera settings, with its calibration."
type CalibrationRow {
  night: String!
  filter: String!
  exposure: Float!
  gain: Float
  offset: Float
  set_temp: Float
  rotator: Float
  lights: Int!
  flat: CalibrationMatch!
  dark: CalibrationMatch!
  bias: CalibrationMatch!
}

"Lights at one gain, offset and exposure near one ladder setpoint with no dark set of that exposure there."
type DarkLibraryGap {
  gain: Float
  offset: Float
  "Exposure of the lights, in seconds."
  exposure: Float
  "Ladder setpoint in °C."
  set_temp: Float!
  lights: Int!
  nights: Int!
  latest_night: String!
  "Exposures of the dark sets at this setpoint, gain and offset, which the stacker scales to these lights for now."
  other_exposures: [Float!]!
}

"The well-covered part of an image, as fractions of its width and height."
type Crop {
  x: Float!
  y: Float!
  w: Float!
  h: Float!
}

"One filter's mosaic of a project's panel masters, plate solved and blended."
type Mosaic {
  filter: String!
  "Panels in the mosaic, of all the project's panels."
  panels: Int!
  panels_total: Int!
  width: Int!
  height: Int!
  updated_at: String!
  "Presigned link to the linear mosaic FITS, valid for an hour."
  master_url: String!
  "Presigned link to the auto-stretched JPEG."
  preview_url: String!
  "Presigned link to the gzipped linear preview (APLP format) for palette mixing."
  linear_url: String!
  "Where the preview is cropped to; the linear preview and FITS are whole."
  crop: Crop
}

"One filter's stacked master for a target: only subs that scored well, added as they arrive."
type FilterMaster {
  filter: String!
  subs: Int!
  exposure_hours: Float!
  "Exposure weighted by sub score."
  effective_hours: Float!
  width: Int!
  height: Int!
  updated_at: String!
  "Presigned link to the linear master FITS, valid for an hour."
  master_url: String!
  "Presigned link to the auto-stretched JPEG."
  preview_url: String!
  "Presigned link to the gzipped linear preview (APLP format) for palette mixing."
  linear_url: String!
  "Where the preview is cropped to; the linear preview and FITS are whole."
  crop: Crop
  "Presigned link to the master as XISF, which PixInsight opens upright and plate solved."
  xisf_url: String
  "Presigned link to the master linear fitted to fit_reference, when the target has other colour or other narrowband filters to match."
  fitted_url: String
  "The filter the linear fitted master is matched to."
  fit_reference: String
  "A comet's master aligned on the comet: preview, FITS and XISF links."
  comet_preview_url: String
  comet_url: String
  comet_xisf_url: String
  "The stacker's min score: subs under it times the target's best score in the filter are left out."
  min_score: Float
  "The lowest score of the subs in the master."
  lowest_score: Float
  "Lights in this filter the stacker has under the master's object name, of any Target Scheduler target or none. Null outside a target page."
  object_lights: Int
  "Subs in the master that are this Target Scheduler target's. Null outside a target page."
  target_subs: Int
}
`, BuiltIn: false},
	{Name: "../../../graph/common.graphqls", Input: `type ImagingStats {
  desired_images: Int!
  accepted_images: Int!
  rejected_images: Int!
  acquired_images: Int!
}

enum ORDER_DIRECTION {
  ASC
  DESC
}

extend type Query {
  version: String!
  commit: String!
}
`, BuiltIn: false},
	{Name: "../../../graph/other.graphqls", Input: `extend type Query {
  "Objects with lights that Target Scheduler did not record and no Target Scheduler target, linked or of the same name, such as comets and targets imaged before it. Empty when the worker is not configured."
  otherTargets: [OtherTarget!]!
  otherTarget(name: String!): OtherTarget
}

"An object with no Target Scheduler target, known from its files."
type OtherTarget {
  name: String!
  lights: Int!
  "Lights Target Scheduler recorded: a target GUID in the header or an acquired image row for the file."
  recorded: Int!
  "Lights in its masters."
  stacked: Int!
  nights: Int!
  first_night: String
  last_night: String
  cover: ProjectCover
  masters: [FilterMaster!]!
}
`, BuiltIn: false},
	{Name: "../../../graph/project.graphqls", Input: `extend type Query {
  projects(orderBy: ProjectOrderBy): [Project!]!
  project(id: ID!): Project
}

enum ProjectOrderField {
  CREATE_DATE
  ACTIVE_DATE
  PRIORITY
  STATE
  NAME
  LAST_IMAGE_DATE
  PROGRESS
  MOSAIC
}

input ProjectOrderBy {
  field: ProjectOrderField!
  direction: ORDER_DIRECTION!
}

enum ProjectState {
  DRAFT
  ACTIVE
  INACTIVE
  CLOSED
}

enum ProjectPriority {
  LOW
  NORMAL
  HIGH
}

type Project {
  id: ID!
  profile_id: String!
  name: String!
  description: String
  state: ProjectState
  priority: ProjectPriority
  create_date: Int
  active_date: Int
  inactive_date: Int
  minimum_time: Int
  minimum_altitude: Float
  use_custom_horizon: Boolean
  horizon_offset: Float
  meridian_window: Int
  filter_switch_frequency: Int
  dither_every: Int
  enable_grader: Boolean
  is_mosaic: Boolean
  # Maybe an enum or bool
  flats_handling: Int
  maximum_altitude: Float
  smart_exposure_order: Int
  targets: [Target!]!
  stats: ProjectStats!
  "Mosaics of the project's panels, one per filter. Empty unless its targets are panels."
  mosaics: [Mosaic!]!
  "A preview for the project's card: its mosaic, or its targets' master with the most effective exposure."
  cover: ProjectCover
}

type ProjectCover {
  "RGB+Ha, RGB, SHO or HOO for a colour composite; empty for one filter."
  palette: String!
  "The filter, for a single-filter preview."
  filter: String!
  preview_url: String!
  mosaic: Boolean!
  "When the picture last changed; its link changes on every request."
  updated_at: String!
  "For a mosaic cover, panels in its mosaic; for a colour mosaic, the fewest in any filter."
  panels: Int
  panels_total: Int
}

type ProjectStats {
  imaging: ImagingStats!
  last_image_date: Int
  "Enabled exposure plans."
  plans: Int!
  "Enabled exposure plans whose accepted images reached their desired count."
  plans_met: Int!
}
`, BuiltIn: false},
	{Name: "../../../graph/target.graphqls", Input: `extend type Query {
  targets(orderBy: TargetOrderBy): [Target!]!
  target(id: ID!): Target
}

enum TargetOrderField {
  NAME
  LAST_IMAGE_DATE
  ACTIVE
  PROGRESS
}

input TargetOrderBy {
  field: TargetOrderField!
  direction: ORDER_DIRECTION!
}

enum Epoch {
  JNOW
  B1950
  J2000
  J2050
}

type Target {
  id: ID!
  name: String!
  active: Boolean!
  ra: Float
  dec: Float
  epoch: Epoch!
  rotation: Float
  region_of_interest: Float!
  project: Project
  stats: TargetStats!
  "Every acquired sub for this target, with the stacker's score and status."
  subframes: [Subframe!]!
  "Calibration coverage per night of lights, newest first. Empty when the worker is not configured."
  calibration: [CalibrationRow!]!
  "Stacked masters, one per filter. Empty when the stacker is not configured."
  masters: [FilterMaster!]!
}

type TargetStats {
  last_image_date: Int
  total: ImagingStats!
  filters: [TargetFilterStats!]!
  "Nominal versus effective integration per filter and exposure length."
  quality: [FilterQuality!]!
}

"One exposure plan of the target, with its images counted by plan."
type TargetFilterStats {
  filter_name: String!
  "The exposure template the plan uses."
  template_name: String
  "The plan's exposure in seconds: its own when set, else the template's default."
  exposure: Float
  "plan or template: where the exposure comes from."
  exposure_source: String
  "Null when the plan has no enabled value."
  enabled: Boolean
  gain: Int
  offset: Int
  imaging: ImagingStats!
}

enum GradingStatus {
  PENDING
  ACCEPTED
  REJECTED
}

"""
A sub as astro-stacker judged it. Its score, weight and status are the
stacker's own, so this page always agrees with what is in the masters.
"""
type Subframe {
  id: ID!
  acquired_date: Int
  filter_name: String!
  exposure_time: Float
  grading_status: GradingStatus!
  reject_reason: String
  file_name: String
  "ADU median above the pedestal the stacker scored the sub with. Null when the stacker has no measure of it; sky_missing says why."
  sky: Float
  "Why sky is null."
  sky_missing: String
  "The pedestal taken off the ADU median, in ADU. Null for a sub that came calibrated."
  pedestal_adu: Float
  "Where the pedestal comes from: bias (measured from a master bias), configured, or calibrated."
  pedestal_source: String
  "The pedestal's basis in words, such as which master bias it was measured from."
  pedestal_basis: String
  hfr: Float
  fwhm: Float
  stars: Int
  eccentricity: Float
  guiding_rms_arcsec: Float
  airmass: Float
  """
  The stacker's score: the sub's worth against the best tenth of subs for its
  filter and exposure, times its transparency squared. Null until the stacker
  has processed the sub.
  """
  score: Float
  "Why score is null."
  score_missing: String
  "What the sub adds to its master, score × exposure in seconds. Null until processed."
  weight: Float
  "The best score of this target's subs in the filter, as the stacker scores them now."
  target_best: Float
  "The stacker's cut: subs scoring under it are left out (min score × target_best)."
  cut: Float
  "The sub's starlight against the best subs of its field, 0 to 1, squared into its score. Null when not measured."
  transparency: Float
  "How transparency was measured: photometry (the stacker's star photometry) or sky_excess (light above the sky in Target Scheduler's record)."
  transparency_source: String
  "Why transparency is not measured; the score then leaves it out."
  transparency_missing: String
  """
  What the stacker made of the sub: pending (not processed yet), added,
  low_score, unmeasured (an input to its score is missing), moon,
  off_target, rejected (in Target Scheduler, not by the stacker),
  no_metadata, calibration, registration, failed, dead, recalibrate,
  duplicate, or unreachable (the stacker could not be asked).
  """
  stack_status: String!
  "Why the sub is not in its master, or what it waits for. Null for a stacked sub."
  stack_reason: String
  """
  Whether the stacker's star photometry is in the sub's transparency yet:
  pending, measured or failed. Null when the stacker has no such file.
  """
  photometry: String
  "Presigned link to an auto-stretched JPEG of the sub, valid for an hour. Null until the worker has rendered it."
  preview_url: String
}

type FilterQuality {
  filter_name: String!
  exposure_time: Float!
  "Subs the stacker judges: all but those Target Scheduler rejected itself, and duplicate files."
  subframes: Int!
  "Subs the stacker put in the master."
  stacked: Int!
  "Subs the stacker hasn't processed yet."
  pending: Int!
  nominal_hours: Float!
  "The stacker's weights (score × exposure) of the subs it stacked: hours of good-conditions data in the master."
  effective_hours: Float!
  median_sky: Float
  "What median_sky is measured against: the pedestals of its subs."
  sky_basis: String
  median_hfr: Float
  "Subs rejected in Target Scheduler, not by the stacker; left out of these counts."
  rejected_in_scheduler: Int!
  "Subs the stacker left out for a score under its cut."
  below_cut: Int!
  "Subs the stacker could not score for a missing input."
  unmeasured: Int!
  "The stacker's min score: the cut is this times the target's best score in the filter."
  min_score: Float
  "This target's best score in the filter, as the stacker scores it now."
  target_best: Float
  cut: Float
  "The reference raw weight, 1/(sky × HFR⁴), scores are relative to: the reference_percentile of the reference_subs subs of this filter and exposure, of every target."
  reference_weight: Float
  reference_subs: Int
  reference_percentile: Float
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// childFields_* functions provide shared child field context lookups.
// Each function is generated once per unique object type, deduplicating the
// switch statements that were previously inlined in every fieldContext_* function.

func (ec *executionContext) childFields_CalibrationBasis(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "night":
		return ec.fieldContext_CalibrationBasis_night(ctx, field)
	case "exposure":
		return ec.fieldContext_CalibrationBasis_exposure(ctx, field)
	case "gain":
		return ec.fieldContext_CalibrationBasis_gain(ctx, field)
	case "offset":
		return ec.fieldContext_CalibrationBasis_offset(ctx, field)
	case "set_temp":
		return ec.fieldContext_CalibrationBasis_set_temp(ctx, field)
	case "bin_x":
		return ec.fieldContext_CalibrationBasis_bin_x(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type CalibrationBasis", field.Name)
}

func (ec *executionContext) childFields_CalibrationMatch(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "quality":
		return ec.fieldContext_CalibrationMatch_quality(ctx, field)
	case "night":
		return ec.fieldContext_CalibrationMatch_night(ctx, field)
	case "frames":
		return ec.fieldContext_CalibrationMatch_frames(ctx, field)
	case "age_days":
		return ec.fieldContext_CalibrationMatch_age_days(ctx, field)
	case "temp_off":
		return ec.fieldContext_CalibrationMatch_temp_off(ctx, field)
	case "set_temp":
		return ec.fieldContext_CalibrationMatch_set_temp(ctx, field)
	case "rotation_mismatch":
		return ec.fieldContext_CalibrationMatch_rotation_mismatch(ctx, field)
	case "scaled":
		return ec.fieldContext_CalibrationMatch_scaled(ctx, field)
	case "exposure":
		return ec.fieldContext_CalibrationMatch_exposure(ctx, field)
	case "source":
		return ec.fieldContext_CalibrationMatch_source(ctx, field)
	case "master":
		return ec.fieldContext_CalibrationMatch_master(ctx, field)
	case "basis":
		return ec.fieldContext_CalibrationMatch_basis(ctx, field)
	case "header_error":
		return ec.fieldContext_CalibrationMatch_header_error(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type CalibrationMatch", field.Name)
}

func (ec *executionContext) childFields_CalibrationRow(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "night":
		return ec.fieldContext_CalibrationRow_night(ctx, field)
	case "filter":
		return ec.fieldContext_CalibrationRow_filter(ctx, field)
	case "exposure":
		return ec.fieldContext_CalibrationRow_exposure(ctx, field)
	case "gain":
		return ec.fieldContext_CalibrationRow_gain(ctx, field)
	case "offset":
		return ec.fieldContext_CalibrationRow_offset(ctx, field)
	case "set_temp":
		return ec.fieldContext_CalibrationRow_set_temp(ctx, field)
	case "rotator":
		return ec.fieldContext_CalibrationRow_rotator(ctx, field)
	case "lights":
		return ec.fieldContext_CalibrationRow_lights(ctx, field)
	case "flat":
		return ec.fieldContext_CalibrationRow_flat(ctx, field)
	case "dark":
		return ec.fieldContext_CalibrationRow_dark(ctx, field)
	case "bias":
		return ec.fieldContext_CalibrationRow_bias(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type CalibrationRow", field.Name)
}

func (ec *executionContext) childFields_Crop(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "x":
		return ec.fieldContext_Crop_x(ctx, field)
	case "y":
		return ec.fieldContext_Crop_y(ctx, field)
	case "w":
		return ec.fieldContext_Crop_w(ctx, field)
	case "h":
		return ec.fieldContext_Crop_h(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Crop", field.Name)
}

func (ec *executionContext) childFields_DarkLibrary(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "ladder":
		return ec.fieldContext_DarkLibrary_ladder(ctx, field)
	case "min_frames":
		return ec.fieldContext_DarkLibrary_min_frames(ctx, field)
	case "set_temp_exact_c":
		return ec.fieldContext_DarkLibrary_set_temp_exact_c(ctx, field)
	case "set_temp_scale_max_c":
		return ec.fieldContext_DarkLibrary_set_temp_scale_max_c(ctx, field)
	case "gaps":
		return ec.fieldContext_DarkLibrary_gaps(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type DarkLibrary", field.Name)
}

func (ec *executionContext) childFields_DarkLibraryGap(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "gain":
		return ec.fieldContext_DarkLibraryGap_gain(ctx, field)
	case "offset":
		return ec.fieldContext_DarkLibraryGap_offset(ctx, field)
	case "exposure":
		return ec.fieldContext_DarkLibraryGap_exposure(ctx, field)
	case "set_temp":
		return ec.fieldContext_DarkLibraryGap_set_temp(ctx, field)
	case "lights":
		return ec.fieldContext_DarkLibraryGap_lights(ctx, field)
	case "nights":
		return ec.fieldContext_DarkLibraryGap_nights(ctx, field)
	case "latest_night":
		return ec.fieldContext_DarkLibraryGap_latest_night(ctx, field)
	case "other_exposures":
		return ec.fieldContext_DarkLibraryGap_other_exposures(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type DarkLibraryGap", field.Name)
}

func (ec *executionContext) childFields_FilterMaster(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "filter":
		return ec.fieldContext_FilterMaster_filter(ctx, field)
	case "subs":
		return ec.fieldContext_FilterMaster_subs(ctx, field)
	case "exposure_hours":
		return ec.fieldContext_FilterMaster_exposure_hours(ctx, field)
	case "effective_hours":
		return ec.fieldContext_FilterMaster_effective_hours(ctx, field)
	case "width":
		return ec.fieldContext_FilterMaster_width(ctx, field)
	case "height":
		return ec.fieldContext_FilterMaster_height(ctx, field)
	case "updated_at":
		return ec.fieldContext_FilterMaster_updated_at(ctx, field)
	case "master_url":
		return ec.fieldContext_FilterMaster_master_url(ctx, field)
	case "preview_url":
		return ec.fieldContext_FilterMaster_preview_url(ctx, field)
	case "linear_url":
		return ec.fieldContext_FilterMaster_linear_url(ctx, field)
	case "crop":
		return ec.fieldContext_FilterMaster_crop(ctx, field)
	case "xisf_url":
		return ec.fieldContext_FilterMaster_xisf_url(ctx, field)
	case "fitted_url":
		return ec.fieldContext_FilterMaster_fitted_url(ctx, field)
	case "fit_reference":
		return ec.fieldContext_FilterMaster_fit_reference(ctx, field)
	case "comet_preview_url":
		return ec.fieldContext_FilterMaster_comet_preview_url(ctx, field)
	case "comet_url":
		return ec.fieldContext_FilterMaster_comet_url(ctx, field)
	case "comet_xisf_url":
		return ec.fieldContext_FilterMaster_comet_xisf_url(ctx, field)
	case "min_score":
		return ec.fieldContext_FilterMaster_min_score(ctx, field)
	case "lowest_score":
		return ec.fieldContext_FilterMaster_lowest_score(ctx, field)
	case "object_lights":
		return ec.fieldContext_FilterMaster_object_lights(ctx, field)
	case "target_subs":
		return ec.fieldContext_FilterMaster_target_subs(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type FilterMaster", field.Name)
}

func (ec *executionContext) childFields_FilterQuality(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "filter_name":
		return ec.fieldContext_FilterQuality_filter_name(ctx, field)
	case "exposure_time":
		return ec.fieldContext_FilterQuality_exposure_time(ctx, field)
	case "subframes":
		return ec.fieldContext_FilterQuality_subframes(ctx, field)
	case "stacked":
		return ec.fieldContext_FilterQuality_stacked(ctx, field)
	case "pending":
		return ec.fieldContext_FilterQuality_pending(ctx, field)
	case "nominal_hours":
		return ec.fieldContext_FilterQuality_nominal_hours(ctx, field)
	case "effective_hours":
		return ec.fieldContext_FilterQuality_effective_hours(ctx, field)
	case "median_sky":
		return ec.fieldContext_FilterQuality_median_sky(ctx, field)
	case "sky_basis":
		return ec.fieldContext_FilterQuality_sky_basis(ctx, field)
	case "median_hfr":
		return ec.fieldContext_FilterQuality_median_hfr(ctx, field)
	case "rejected_in_scheduler":
		return ec.fieldContext_FilterQuality_rejected_in_scheduler(ctx, field)
	case "below_cut":
		return ec.fieldContext_FilterQuality_below_cut(ctx, field)
	case "unmeasured":
		return ec.fieldContext_FilterQuality_unmeasured(ctx, field)
	case "min_score":
		return ec.fieldContext_FilterQuality_min_score(ctx, field)
	case "target_best":
		return ec.fieldContext_FilterQuality_target_best(ctx, field)
	case "cut":
		return ec.fieldContext_FilterQuality_cut(ctx, field)
	case "reference_weight":
		return ec.fieldContext_FilterQuality_reference_weight(ctx, field)
	case "reference_subs":
		return ec.fieldContext_FilterQuality_reference_subs(ctx, field)
	case "reference_percentile":
		return ec.fieldContext_FilterQuality_reference_percentile(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type FilterQuality", field.Name)
}

func (ec *executionContext) childFields_ImagingStats(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "desired_images":
		return ec.fieldContext_ImagingStats_desired_images(ctx, field)
	case "accepted_images":
		return ec.fieldContext_ImagingStats_accepted_images(ctx, field)
	case "rejected_images":
		return ec.fieldContext_ImagingStats_rejected_images(ctx, field)
	case "acquired_images":
		return ec.fieldContext_ImagingStats_acquired_images(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type ImagingStats", field.Name)
}

func (ec *executionContext) childFields_Mosaic(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "filter":
		return ec.fieldContext_Mosaic_filter(ctx, field)
	case "panels":
		return ec.fieldContext_Mosaic_panels(ctx, field)
	case "panels_total":
		return ec.fieldContext_Mosaic_panels_total(ctx, field)
	case "width":
		return ec.fieldContext_Mosaic_width(ctx, field)
	case "height":
		return ec.fieldContext_Mosaic_height(ctx, field)
	case "updated_at":
		return ec.fieldContext_Mosaic_updated_at(ctx, field)
	case "master_url":
		return ec.fieldContext_Mosaic_master_url(ctx, field)
	case "preview_url":
		return ec.fieldContext_Mosaic_preview_url(ctx, field)
	case "linear_url":
		return ec.fieldContext_Mosaic_linear_url(ctx, field)
	case "crop":
		return ec.fieldContext_Mosaic_crop(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Mosaic", field.Name)
}

func (ec *executionContext) childFields_OtherTarget(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext_OtherTarget_name(ctx, field)
	case "lights":
		return ec.fieldContext_OtherTarget_lights(ctx, field)
	case "recorded":
		return ec.fieldContext_OtherTarget_recorded(ctx, field)
	case "stacked":
		return ec.fieldContext_OtherTarget_stacked(ctx, field)
	case "nights":
		return ec.fieldContext_OtherTarget_nights(ctx, field)
	case "first_night":
		return ec.fieldContext_OtherTarget_first_night(ctx, field)
	case "last_night":
		return ec.fieldContext_OtherTarget_last_night(ctx, field)
	case "cover":
		return ec.fieldContext_OtherTarget_cover(ctx, field)
	case "masters":
		return ec.fieldContext_OtherTarget_masters(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type OtherTarget", field.Name)
}

func (ec *executionContext) childFields_Project(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Project_id(ctx, field)
	case "profile_id":
		return ec.fieldContext_Project_profile_id(ctx, field)
	case "name":
		return ec.fieldContext_Project_name(ctx, field)
	case "description":
		return ec.fieldContext_Project_description(ctx, field)
	case "state":
		return ec.fieldContext_Project_state(ctx, field)
	case "priority":
		return ec.fieldContext_Project_priority(ctx, field)
	case "create_date":
		return ec.fieldContext_Project_create_date(ctx, field)
	case "active_date":
		return ec.fieldContext_Project_active_date(ctx, field)
	case "inactive_date":
		return ec.fieldContext_Project_inactive_date(ctx, field)
	case "minimum_time":
		return ec.fieldContext_Project_minimum_time(ctx, field)
	case "minimum_altitude":
		return ec.fieldContext_Project_minimum_altitude(ctx, field)
	case "use_custom_horizon":
		return ec.fieldContext_Project_use_custom_horizon(ctx, field)
	case "horizon_offset":
		return ec.fieldContext_Project_horizon_offset(ctx, field)
	case "meridian_window":
		return ec.fieldContext_Project_meridian_window(ctx, field)
	case "filter_switch_frequency":
		return ec.fieldContext_Project_filter_switch_frequency(ctx, field)
	case "dither_every":
		return ec.fieldContext_Project_dither_every(ctx, field)
	case "enable_grader":
		return ec.fieldContext_Project_enable_grader(ctx, field)
	case "is_mosaic":
		return ec.fieldContext_Project_is_mosaic(ctx, field)
	case "flats_handling":
		return ec.fieldContext_Project_flats_handling(ctx, field)
	case "maximum_altitude":
		return ec.fieldContext_Project_maximum_altitude(ctx, field)
	case "smart_exposure_order":
		return ec.fieldContext_Project_smart_exposure_order(ctx, field)
	case "targets":
		return ec.fieldContext_Project_targets(ctx, field)
	case "stats":
		return ec.fieldContext_Project_stats(ctx, field)
	case "mosaics":
		return ec.fieldContext_Project_mosaics(ctx, field)
	case "cover":
		return ec.fieldContext_Project_cover(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Project", field.Name)
}

func (ec *executionContext) childFields_ProjectCover(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "palette":
		return ec.fieldContext_ProjectCover_palette(ctx, field)
	case "filter":
		return ec.fieldContext_ProjectCover_filter(ctx, field)
	case "preview_url":
		return ec.fieldContext_ProjectCover_preview_url(ctx, field)
	case "mosaic":
		return ec.fieldContext_ProjectCover_mosaic(ctx, field)
	case "updated_at":
		return ec.fieldContext_ProjectCover_updated_at(ctx, field)
	case "panels":
		return ec.fieldContext_ProjectCover_panels(ctx, field)
	case "panels_total":
		return ec.fieldContext_ProjectCover_panels_total(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type ProjectCover", field.Name)
}

func (ec *executionContext) childFields_ProjectStats(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "imaging":
		return ec.fieldContext_ProjectStats_imaging(ctx, field)
	case "last_image_date":
		return ec.fieldContext_ProjectStats_last_image_date(ctx, field)
	case "plans":
		return ec.fieldContext_ProjectStats_plans(ctx, field)
	case "plans_met":
		return ec.fieldContext_ProjectStats_plans_met(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type ProjectStats", field.Name)
}

func (ec *executionContext) childFields_Subframe(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Subframe_id(ctx, field)
	case "acquired_date":
		return ec.fieldContext_Subframe_acquired_date(ctx, field)
	case "filter_name":
		return ec.fieldContext_Subframe_filter_name(ctx, field)
	case "exposure_time":
		return ec.fieldContext_Subframe_exposure_time(ctx, field)
	case "grading_status":
		return ec.fieldContext_Subframe_grading_status(ctx, field)
	case "reject_reason":
		return ec.fieldContext_Subframe_reject_reason(ctx, field)
	case "file_name":
		return ec.fieldContext_Subframe_file_name(ctx, field)
	case "sky":
		return ec.fieldContext_Subframe_sky(ctx, field)
	case "sky_missing":
		return ec.fieldContext_Subframe_sky_missing(ctx, field)
	case "pedestal_adu":
		return ec.fieldContext_Subframe_pedestal_adu(ctx, field)
	case "pedestal_source":
		return ec.fieldContext_Subframe_pedestal_source(ctx, field)
	case "pedestal_basis":
		return ec.fieldContext_Subframe_pedestal_basis(ctx, field)
	case "hfr":
		return ec.fieldContext_Subframe_hfr(ctx, field)
	case "fwhm":
		return ec.fieldContext_Subframe_fwhm(ctx, field)
	case "stars":
		return ec.fieldContext_Subframe_stars(ctx, field)
	case "eccentricity":
		return ec.fieldContext_Subframe_eccentricity(ctx, field)
	case "guiding_rms_arcsec":
		return ec.fieldContext_Subframe_guiding_rms_arcsec(ctx, field)
	case "airmass":
		return ec.fieldContext_Subframe_airmass(ctx, field)
	case "score":
		return ec.fieldContext_Subframe_score(ctx, field)
	case "score_missing":
		return ec.fieldContext_Subframe_score_missing(ctx, field)
	case "weight":
		return ec.fieldContext_Subframe_weight(ctx, field)
	case "target_best":
		return ec.fieldContext_Subframe_target_best(ctx, field)
	case "cut":
		return ec.fieldContext_Subframe_cut(ctx, field)
	case "transparency":
		return ec.fieldContext_Subframe_transparency(ctx, field)
	case "transparency_source":
		return ec.fieldContext_Subframe_transparency_source(ctx, field)
	case "transparency_missing":
		return ec.fieldContext_Subframe_transparency_missing(ctx, field)
	case "stack_status":
		return ec.fieldContext_Subframe_stack_status(ctx, field)
	case "stack_reason":
		return ec.fieldContext_Subframe_stack_reason(ctx, field)
	case "photometry":
		return ec.fieldContext_Subframe_photometry(ctx, field)
	case "preview_url":
		return ec.fieldContext_Subframe_preview_url(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Subframe", field.Name)
}

func (ec *executionContext) childFields_Target(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Target_id(ctx, field)
	case "name":
		return ec.fieldContext_Target_name(ctx, field)
	case "active":
		return ec.fieldContext_Target_active(ctx, field)
	case "ra":
		return ec.fieldContext_Target_ra(ctx, field)
	case "dec":
		return ec.fieldContext_Target_dec(ctx, field)
	case "epoch":
		return ec.fieldContext_Target_epoch(ctx, field)
	case "rotation":
		return ec.fieldContext_Target_rotation(ctx, field)
	case "region_of_interest":
		return ec.fieldContext_Target_region_of_interest(ctx, field)
	case "project":
		return ec.fieldContext_Target_project(ctx, field)
	case "stats":
		return ec.fieldContext_Target_stats(ctx, field)
	case "subframes":
		return ec.fieldContext_Target_subframes(ctx, field)
	case "calibration":
		return ec.fieldContext_Target_calibration(ctx, field)
	case "masters":
		return ec.fieldContext_Target_masters(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Target", field.Name)
}

func (ec *executionContext) childFields_TargetFilterStats(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "filter_name":
		return ec.fieldContext_TargetFilterStats_filter_name(ctx, field)
	case "template_name":
		return ec.fieldContext_TargetFilterStats_template_name(ctx, field)
	case "exposure":
		return ec.fieldContext_TargetFilterStats_exposure(ctx, field)
	case "exposure_source":
		return ec.fieldContext_TargetFilterStats_exposure_source(ctx, field)
	case "enabled":
		return ec.fieldContext_TargetFilterStats_enabled(ctx, field)
	case "gain":
		return ec.fieldContext_TargetFilterStats_gain(ctx, field)
	case "offset":
		return ec.fieldContext_TargetFilterStats_offset(ctx, field)
	case "imaging":
		return ec.fieldContext_TargetFilterStats_imaging(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type TargetFilterStats", field.Name)
}

func (ec *executionContext) childFields_TargetStats(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "last_image_date":
		return ec.fieldContext_TargetStats_last_image_date(ctx, field)
	case "total":
		return ec.fieldContext_TargetStats_total(ctx, field)
	case "filters":
		return ec.fieldContext_TargetStats_filters(ctx, field)
	case "quality":
		return ec.fieldContext_TargetStats_quality(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type TargetStats", field.Name)
}

func (ec *executionContext) childFields___Directive(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___Directive_name(ctx, field)
	case "description":
		return ec.fieldContext___Directive_description(ctx, field)
	case "isRepeatable":
		return ec.fieldContext___Directive_isRepeatable(ctx, field)
	case "locations":
		return ec.fieldContext___Directive_locations(ctx, field)
	case "args":
		return ec.fieldContext___Directive_args(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Directive", field.Name)
}

func (ec *executionContext) childFields___EnumValue(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___EnumValue_name(ctx, field)
	case "description":
		return ec.fieldContext___EnumValue_description(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___EnumValue_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___EnumValue_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __EnumValue", field.Name)
}

func (ec *executionContext) childFields___Field(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___Field_name(ctx, field)
	case "description":
		return ec.fieldContext___Field_description(ctx, field)
	case "args":
		return ec.fieldContext___Field_args(ctx, field)
	case "type":
		return ec.fieldContext___Field_type(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___Field_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___Field_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Field", field.Name)
}

func (ec *executionContext) childFields___InputValue(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___InputValue_name(ctx, field)
	case "description":
		return ec.fieldContext___InputValue_description(ctx, field)
	case "type":
		return ec.fieldContext___InputValue_type(ctx, field)
	case "defaultValue":
		return ec.fieldContext___InputValue_defaultValue(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___InputValue_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___InputValue_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __InputValue", field.Name)
}

func (ec *executionContext) childFields___Schema(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "description":
		return ec.fieldContext___Schema_description(ctx, field)
	case "types":
		return ec.fieldContext___Schema_types(ctx, field)
	case "queryType":
		return ec.fieldContext___Schema_queryType(ctx, field)
	case "mutationType":
		return ec.fieldContext___Schema_mutationType(ctx, field)
	case "subscriptionType":
		return ec.fieldContext___Schema_subscriptionType(ctx, field)
	case "directives":
		return ec.fieldContext___Schema_directives(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Schema", field.Name)
}

func (ec *executionContext) childFields___Type(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "kind":
		return ec.fieldContext___Type_kind(ctx, field)
	case "name":
		return ec.fieldContext___Type_name(ctx, field)
	case "description":
		return ec.fieldContext___Type_description(ctx, field)
	case "specifiedByURL":
		return ec.fieldContext___Type_specifiedByURL(ctx, field)
	case "fields":
		return ec.fieldContext___Type_fields(ctx, field)
	case "interfaces":
		return ec.fieldContext___Type_interfaces(ctx, field)
	case "possibleTypes":
		return ec.fieldContext___Type_possibleTypes(ctx, field)
	case "enumValues":
		return ec.fieldContext___Type_enumValues(ctx, field)
	case "inputFields":
		return ec.fieldContext___Type_inputFields(ctx, field)
	case "ofType":
		return ec.fieldContext___Type_ofType(ctx, field)
	case "isOneOf":
		return ec.fieldContext___Type_isOneOf(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Type", field.Name)
}
