// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CalibrationMatch struct {
	Quality CalibrationQuality `json:"quality"`
	// Night the calibration frames were taken.
	Night  *string `json:"night,omitempty"`
	Frames *int32  `json:"frames,omitempty"`
	// Nights between the lights and the calibration.
	AgeDays int32 `json:"age_days"`
	// Dark setpoint difference in °C.
	TempOff *float64 `json:"temp_off,omitempty"`
	// Dark setpoint in °C.
	SetTemp *float64 `json:"set_temp,omitempty"`
	// The flat was taken at another rotator angle.
	RotationMismatch bool `json:"rotation_mismatch"`
	// The dark's thermal signal must be scaled to the lights.
	Scaled bool `json:"scaled"`
}

// One night of lights sharing a filter and camera settings, with its calibration.
type CalibrationRow struct {
	Night    string            `json:"night"`
	Filter   string            `json:"filter"`
	Exposure float64           `json:"exposure"`
	Gain     *float64          `json:"gain,omitempty"`
	Offset   *float64          `json:"offset,omitempty"`
	SetTemp  *float64          `json:"set_temp,omitempty"`
	Rotator  *float64          `json:"rotator,omitempty"`
	Lights   int32             `json:"lights"`
	Flat     *CalibrationMatch `json:"flat"`
	Dark     *CalibrationMatch `json:"dark"`
	Bias     *CalibrationMatch `json:"bias"`
}

// The well-covered part of an image, as fractions of its width and height.
type Crop struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	W float64 `json:"w"`
	H float64 `json:"h"`
}

type DarkLibraryGap struct {
	Gain        *float64 `json:"gain,omitempty"`
	Offset      *float64 `json:"offset,omitempty"`
	SetTemp     float64  `json:"set_temp"`
	Lights      int32    `json:"lights"`
	Nights      int32    `json:"nights"`
	LatestNight string   `json:"latest_night"`
}

// One filter's stacked master for a target: only subs that scored well, added as they arrive.
type FilterMaster struct {
	Filter        string  `json:"filter"`
	Subs          int32   `json:"subs"`
	ExposureHours float64 `json:"exposure_hours"`
	// Exposure weighted by sub score.
	EffectiveHours float64 `json:"effective_hours"`
	Width          int32   `json:"width"`
	Height         int32   `json:"height"`
	UpdatedAt      string  `json:"updated_at"`
	// Presigned link to the linear master FITS, valid for an hour.
	MasterURL string `json:"master_url"`
	// Presigned link to the auto-stretched JPEG.
	PreviewURL string `json:"preview_url"`
	// Presigned link to the gzipped linear preview (APLP format) for palette mixing.
	LinearURL string `json:"linear_url"`
	// Where the preview is cropped to; the linear preview and FITS are whole.
	Crop *Crop `json:"crop,omitempty"`
	// Presigned link to the master as XISF, which PixInsight opens upright and plate solved.
	XisfURL *string `json:"xisf_url,omitempty"`
	// Presigned link to the master linear fitted to fit_reference, when the target has other colour or other narrowband filters to match.
	FittedURL *string `json:"fitted_url,omitempty"`
	// The filter the linear fitted master is matched to.
	FitReference *string `json:"fit_reference,omitempty"`
	// A comet's master aligned on the comet: preview, FITS and XISF links.
	CometPreviewURL *string `json:"comet_preview_url,omitempty"`
	CometURL        *string `json:"comet_url,omitempty"`
	CometXisfURL    *string `json:"comet_xisf_url,omitempty"`
}

type FilterQuality struct {
	FilterName   string  `json:"filter_name"`
	ExposureTime float64 `json:"exposure_time"`
	// Subs the stacker judges: all but those Target Scheduler rejected itself, and duplicate files.
	Subframes int32 `json:"subframes"`
	// Subs the stacker put in the master.
	Stacked int32 `json:"stacked"`
	// Subs the stacker hasn't processed yet.
	Pending      int32   `json:"pending"`
	NominalHours float64 `json:"nominal_hours"`
	// The stacker's weights (score × exposure) of the subs it stacked: hours of good-conditions data in the master.
	EffectiveHours float64  `json:"effective_hours"`
	MedianSky      *float64 `json:"median_sky,omitempty"`
	MedianHfr      *float64 `json:"median_hfr,omitempty"`
}

type ImagingStats struct {
	DesiredImages  int32 `json:"desired_images"`
	AcceptedImages int32 `json:"accepted_images"`
	RejectedImages int32 `json:"rejected_images"`
	AcquiredImages int32 `json:"acquired_images"`
}

// One filter's mosaic of a project's panel masters, plate solved and blended.
type Mosaic struct {
	Filter string `json:"filter"`
	// Panels in the mosaic, of all the project's panels.
	Panels      int32  `json:"panels"`
	PanelsTotal int32  `json:"panels_total"`
	Width       int32  `json:"width"`
	Height      int32  `json:"height"`
	UpdatedAt   string `json:"updated_at"`
	// Presigned link to the linear mosaic FITS, valid for an hour.
	MasterURL string `json:"master_url"`
	// Presigned link to the auto-stretched JPEG.
	PreviewURL string `json:"preview_url"`
	// Presigned link to the gzipped linear preview (APLP format) for palette mixing.
	LinearURL string `json:"linear_url"`
	// Where the preview is cropped to; the linear preview and FITS are whole.
	Crop *Crop `json:"crop,omitempty"`
}

// A target imaged outside Target Scheduler, known only from its files.
type OtherTarget struct {
	Name   string `json:"name"`
	Lights int32  `json:"lights"`
	// Lights in its masters.
	Stacked    int32           `json:"stacked"`
	Nights     int32           `json:"nights"`
	FirstNight *string         `json:"first_night,omitempty"`
	LastNight  *string         `json:"last_night,omitempty"`
	Cover      *ProjectCover   `json:"cover,omitempty"`
	Masters    []*FilterMaster `json:"masters"`
}

type Project struct {
	ID                    int              `json:"id"`
	ProfileID             string           `json:"profile_id"`
	Name                  string           `json:"name"`
	Description           *string          `json:"description,omitempty"`
	State                 *ProjectState    `json:"state,omitempty"`
	Priority              *ProjectPriority `json:"priority,omitempty"`
	CreateDate            *int32           `json:"create_date,omitempty"`
	ActiveDate            *int32           `json:"active_date,omitempty"`
	InactiveDate          *int32           `json:"inactive_date,omitempty"`
	MinimumTime           *int32           `json:"minimum_time,omitempty"`
	MinimumAltitude       *float64         `json:"minimum_altitude,omitempty"`
	UseCustomHorizon      *bool            `json:"use_custom_horizon,omitempty"`
	HorizonOffset         *float64         `json:"horizon_offset,omitempty"`
	MeridianWindow        *int32           `json:"meridian_window,omitempty"`
	FilterSwitchFrequency *int32           `json:"filter_switch_frequency,omitempty"`
	DitherEvery           *int32           `json:"dither_every,omitempty"`
	EnableGrader          *bool            `json:"enable_grader,omitempty"`
	IsMosaic              *bool            `json:"is_mosaic,omitempty"`
	FlatsHandling         *int32           `json:"flats_handling,omitempty"`
	MaximumAltitude       *float64         `json:"maximum_altitude,omitempty"`
	SmartExposureOrder    *int32           `json:"smart_exposure_order,omitempty"`
	Targets               []*Target        `json:"targets"`
	Stats                 *ProjectStats    `json:"stats"`
	// Mosaics of the project's panels, one per filter. Empty unless its targets are panels.
	Mosaics []*Mosaic `json:"mosaics"`
	// A preview for the project's card: its mosaic, or its targets' master with the most effective exposure.
	Cover *ProjectCover `json:"cover,omitempty"`
}

type ProjectCover struct {
	// RGB+Ha, RGB, SHO or HOO for a colour composite; empty for one filter.
	Palette string `json:"palette"`
	// The filter, for a single-filter preview.
	Filter     string `json:"filter"`
	PreviewURL string `json:"preview_url"`
	Mosaic     bool   `json:"mosaic"`
	// When the picture last changed; its link changes on every request.
	UpdatedAt string `json:"updated_at"`
	// For a mosaic cover, panels in its mosaic; for a colour mosaic, the fewest in any filter.
	Panels      *int32 `json:"panels,omitempty"`
	PanelsTotal *int32 `json:"panels_total,omitempty"`
}

type ProjectOrderBy struct {
	Field     ProjectOrderField `json:"field"`
	Direction OrderDirection    `json:"direction"`
}

type ProjectStats struct {
	Imaging       *ImagingStats `json:"imaging"`
	LastImageDate *int32        `json:"last_image_date,omitempty"`
	// Enabled exposure plans.
	Plans int32 `json:"plans"`
	// Enabled exposure plans whose accepted images reached their desired count.
	PlansMet int32 `json:"plans_met"`
}

type Query struct {
}

// A sub as astro-stacker judged it. Its score, weight and status are the
// stacker's own, so this page always agrees with what is in the masters.
type Subframe struct {
	ID            int           `json:"id"`
	AcquiredDate  *int32        `json:"acquired_date,omitempty"`
	FilterName    string        `json:"filter_name"`
	ExposureTime  *float64      `json:"exposure_time,omitempty"`
	GradingStatus GradingStatus `json:"grading_status"`
	RejectReason  *string       `json:"reject_reason,omitempty"`
	FileName      *string       `json:"file_name,omitempty"`
	// ADU median above the camera pedestal, adjusted for the sub's offset.
	Sky              *float64 `json:"sky,omitempty"`
	Hfr              *float64 `json:"hfr,omitempty"`
	Fwhm             *float64 `json:"fwhm,omitempty"`
	Stars            *int32   `json:"stars,omitempty"`
	Eccentricity     *float64 `json:"eccentricity,omitempty"`
	GuidingRmsArcsec *float64 `json:"guiding_rms_arcsec,omitempty"`
	Airmass          *float64 `json:"airmass,omitempty"`
	// The stacker's score: the sub's worth against the best tenth of subs for its
	// filter and exposure, times its transparency squared. Null until the stacker
	// has processed the sub.
	Score *float64 `json:"score,omitempty"`
	// What the sub adds to its master, score × exposure in seconds. Null until processed.
	Weight *float64 `json:"weight,omitempty"`
	// What the stacker made of the sub: pending (not processed yet), added,
	// low_score, moon, off_target, rejected (in Target Scheduler, not by the
	// stacker), no_metadata, calibration, registration, failed, dead,
	// recalibrate or duplicate.
	StackStatus string `json:"stack_status"`
	// Why the sub is not in its master, or what it waits for. Null for a stacked sub.
	StackReason *string `json:"stack_reason,omitempty"`
	// Whether the stacker's star photometry is in the sub's transparency yet:
	// pending, measured or failed. Null when the stacker has no such file.
	Photometry *string `json:"photometry,omitempty"`
	// Presigned link to an auto-stretched JPEG of the sub, valid for an hour. Null until the worker has rendered it.
	PreviewURL *string `json:"preview_url,omitempty"`
}

type Target struct {
	ID               int          `json:"id"`
	Name             string       `json:"name"`
	Active           bool         `json:"active"`
	Ra               *float64     `json:"ra,omitempty"`
	Dec              *float64     `json:"dec,omitempty"`
	Epoch            Epoch        `json:"epoch"`
	Rotation         float64      `json:"rotation"`
	RegionOfInterest float64      `json:"region_of_interest"`
	Project          *Project     `json:"project,omitempty"`
	Stats            *TargetStats `json:"stats"`
	// Every acquired sub for this target, with the stacker's score and status.
	Subframes []*Subframe `json:"subframes"`
	// Calibration coverage per night of lights, newest first. Empty when the worker is not configured.
	Calibration []*CalibrationRow `json:"calibration"`
	// Stacked masters, one per filter. Empty when the stacker is not configured.
	Masters []*FilterMaster `json:"masters"`
}

// One exposure plan of the target, with its images counted by plan.
type TargetFilterStats struct {
	FilterName string `json:"filter_name"`
	// The exposure template the plan uses.
	TemplateName *string `json:"template_name,omitempty"`
	// The plan's exposure in seconds: its own when set, else the template's default.
	Exposure *float64 `json:"exposure,omitempty"`
	// plan or template: where the exposure comes from.
	ExposureSource *string `json:"exposure_source,omitempty"`
	// Null when the plan has no enabled value.
	Enabled *bool         `json:"enabled,omitempty"`
	Gain    *int32        `json:"gain,omitempty"`
	Offset  *int32        `json:"offset,omitempty"`
	Imaging *ImagingStats `json:"imaging"`
}

type TargetOrderBy struct {
	Field     TargetOrderField `json:"field"`
	Direction OrderDirection   `json:"direction"`
}

type TargetStats struct {
	LastImageDate *int32               `json:"last_image_date,omitempty"`
	Total         *ImagingStats        `json:"total"`
	Filters       []*TargetFilterStats `json:"filters"`
	// Nominal versus effective integration per filter and exposure length.
	Quality []*FilterQuality `json:"quality"`
}

type CalibrationQuality string

const (
	CalibrationQualityExact    CalibrationQuality = "EXACT"
	CalibrationQualityFallback CalibrationQuality = "FALLBACK"
	CalibrationQualityMissing  CalibrationQuality = "MISSING"
)

var AllCalibrationQuality = []CalibrationQuality{
	CalibrationQualityExact,
	CalibrationQualityFallback,
	CalibrationQualityMissing,
}

func (e CalibrationQuality) IsValid() bool {
	switch e {
	case CalibrationQualityExact, CalibrationQualityFallback, CalibrationQualityMissing:
		return true
	}
	return false
}

func (e CalibrationQuality) String() string {
	return string(e)
}

func (e *CalibrationQuality) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CalibrationQuality(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CalibrationQuality", str)
	}
	return nil
}

func (e CalibrationQuality) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CalibrationQuality) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CalibrationQuality) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Epoch string

const (
	EpochJnow  Epoch = "JNOW"
	EpochB1950 Epoch = "B1950"
	EpochJ2000 Epoch = "J2000"
	EpochJ2050 Epoch = "J2050"
)

var AllEpoch = []Epoch{
	EpochJnow,
	EpochB1950,
	EpochJ2000,
	EpochJ2050,
}

func (e Epoch) IsValid() bool {
	switch e {
	case EpochJnow, EpochB1950, EpochJ2000, EpochJ2050:
		return true
	}
	return false
}

func (e Epoch) String() string {
	return string(e)
}

func (e *Epoch) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Epoch(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Epoch", str)
	}
	return nil
}

func (e Epoch) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Epoch) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Epoch) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GradingStatus string

const (
	GradingStatusPending  GradingStatus = "PENDING"
	GradingStatusAccepted GradingStatus = "ACCEPTED"
	GradingStatusRejected GradingStatus = "REJECTED"
)

var AllGradingStatus = []GradingStatus{
	GradingStatusPending,
	GradingStatusAccepted,
	GradingStatusRejected,
}

func (e GradingStatus) IsValid() bool {
	switch e {
	case GradingStatusPending, GradingStatusAccepted, GradingStatusRejected:
		return true
	}
	return false
}

func (e GradingStatus) String() string {
	return string(e)
}

func (e *GradingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GradingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GradingStatus", str)
	}
	return nil
}

func (e GradingStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GradingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GradingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ORDER_DIRECTION", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectOrderField string

const (
	ProjectOrderFieldCreateDate    ProjectOrderField = "CREATE_DATE"
	ProjectOrderFieldActiveDate    ProjectOrderField = "ACTIVE_DATE"
	ProjectOrderFieldPriority      ProjectOrderField = "PRIORITY"
	ProjectOrderFieldState         ProjectOrderField = "STATE"
	ProjectOrderFieldName          ProjectOrderField = "NAME"
	ProjectOrderFieldLastImageDate ProjectOrderField = "LAST_IMAGE_DATE"
	ProjectOrderFieldProgress      ProjectOrderField = "PROGRESS"
	ProjectOrderFieldMosaic        ProjectOrderField = "MOSAIC"
)

var AllProjectOrderField = []ProjectOrderField{
	ProjectOrderFieldCreateDate,
	ProjectOrderFieldActiveDate,
	ProjectOrderFieldPriority,
	ProjectOrderFieldState,
	ProjectOrderFieldName,
	ProjectOrderFieldLastImageDate,
	ProjectOrderFieldProgress,
	ProjectOrderFieldMosaic,
}

func (e ProjectOrderField) IsValid() bool {
	switch e {
	case ProjectOrderFieldCreateDate, ProjectOrderFieldActiveDate, ProjectOrderFieldPriority, ProjectOrderFieldState, ProjectOrderFieldName, ProjectOrderFieldLastImageDate, ProjectOrderFieldProgress, ProjectOrderFieldMosaic:
		return true
	}
	return false
}

func (e ProjectOrderField) String() string {
	return string(e)
}

func (e *ProjectOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectOrderField", str)
	}
	return nil
}

func (e ProjectOrderField) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectPriority string

const (
	ProjectPriorityLow    ProjectPriority = "LOW"
	ProjectPriorityNormal ProjectPriority = "NORMAL"
	ProjectPriorityHigh   ProjectPriority = "HIGH"
)

var AllProjectPriority = []ProjectPriority{
	ProjectPriorityLow,
	ProjectPriorityNormal,
	ProjectPriorityHigh,
}

func (e ProjectPriority) IsValid() bool {
	switch e {
	case ProjectPriorityLow, ProjectPriorityNormal, ProjectPriorityHigh:
		return true
	}
	return false
}

func (e ProjectPriority) String() string {
	return string(e)
}

func (e *ProjectPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectPriority", str)
	}
	return nil
}

func (e ProjectPriority) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectState string

const (
	ProjectStateDraft    ProjectState = "DRAFT"
	ProjectStateActive   ProjectState = "ACTIVE"
	ProjectStateInactive ProjectState = "INACTIVE"
	ProjectStateClosed   ProjectState = "CLOSED"
)

var AllProjectState = []ProjectState{
	ProjectStateDraft,
	ProjectStateActive,
	ProjectStateInactive,
	ProjectStateClosed,
}

func (e ProjectState) IsValid() bool {
	switch e {
	case ProjectStateDraft, ProjectStateActive, ProjectStateInactive, ProjectStateClosed:
		return true
	}
	return false
}

func (e ProjectState) String() string {
	return string(e)
}

func (e *ProjectState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectState", str)
	}
	return nil
}

func (e ProjectState) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TargetOrderField string

const (
	TargetOrderFieldName          TargetOrderField = "NAME"
	TargetOrderFieldLastImageDate TargetOrderField = "LAST_IMAGE_DATE"
	TargetOrderFieldActive        TargetOrderField = "ACTIVE"
	TargetOrderFieldProgress      TargetOrderField = "PROGRESS"
)

var AllTargetOrderField = []TargetOrderField{
	TargetOrderFieldName,
	TargetOrderFieldLastImageDate,
	TargetOrderFieldActive,
	TargetOrderFieldProgress,
}

func (e TargetOrderField) IsValid() bool {
	switch e {
	case TargetOrderFieldName, TargetOrderFieldLastImageDate, TargetOrderFieldActive, TargetOrderFieldProgress:
		return true
	}
	return false
}

func (e TargetOrderField) String() string {
	return string(e)
}

func (e *TargetOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TargetOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TargetOrderField", str)
	}
	return nil
}

func (e TargetOrderField) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TargetOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TargetOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
