package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/USA-RedDragon/astro-processing/internal/server/graph"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
)

// DarkLibrary is the resolver for the darkLibrary field.
func (r *queryResolver) DarkLibrary(ctx context.Context) (*model.DarkLibrary, error) {
	if r.worker == nil {
		return nil, nil
	}
	rep, err := r.worker.DarkGaps(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get dark library gaps: %w", err)
	}
	return toDarkLibrary(rep), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
