package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/USA-RedDragon/astro-processing/internal/server/graph"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
)

// DarkLibraryGaps is the resolver for the darkLibraryGaps field.
func (r *queryResolver) DarkLibraryGaps(ctx context.Context) ([]*model.DarkLibraryGap, error) {
	if r.worker == nil {
		return []*model.DarkLibraryGap{}, nil
	}
	gaps, err := r.worker.DarkGaps(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get dark library gaps: %w", err)
	}
	out := make([]*model.DarkLibraryGap, 0, len(gaps))
	for _, g := range gaps {
		out = append(out, &model.DarkLibraryGap{
			Gain: g.Gain, Offset: g.Offset, SetTemp: g.SetTemp,
			Lights: int32(g.Lights), Nights: int32(g.Nights), LatestNight: g.LatestNight,
		})
	}
	return out, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
