package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"time"

	"github.com/USA-RedDragon/astro-processing/internal/server/graph"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
)

// Cover is the resolver for the cover field.
func (r *otherTargetResolver) Cover(ctx context.Context, obj *model.OtherTarget) (*model.ProjectCover, error) {
	if r.worker == nil {
		return nil, nil
	}
	covers, err := r.cachedCovers(ctx)
	if err != nil {
		// A card without a picture is better than a failed page.
		return nil, nil
	}
	c, ok := covers.Objects[obj.Name]
	if !ok {
		return nil, nil
	}
	return &model.ProjectCover{Palette: c.Palette, Filter: c.Filter, PreviewURL: c.PreviewURL,
		UpdatedAt: c.UpdatedAt.UTC().Format(time.RFC3339)}, nil
}

// Masters is the resolver for the masters field.
func (r *otherTargetResolver) Masters(ctx context.Context, obj *model.OtherTarget) ([]*model.FilterMaster, error) {
	return r.masters(ctx, obj.Name)
}

// OtherTargets is the resolver for the otherTargets field.
func (r *queryResolver) OtherTargets(ctx context.Context) ([]*model.OtherTarget, error) {
	if r.worker == nil {
		return []*model.OtherTarget{}, nil
	}
	objects, err := r.worker.Objects(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list targets: %w", err)
	}
	out := []*model.OtherTarget{}
	for _, o := range objects {
		if isOther(o) {
			out = append(out, graphObject(o))
		}
	}
	return out, nil
}

// OtherTarget is the resolver for the otherTarget field.
func (r *queryResolver) OtherTarget(ctx context.Context, name string) (*model.OtherTarget, error) {
	if r.worker == nil {
		return nil, nil
	}
	objects, err := r.worker.Objects(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list targets: %w", err)
	}
	for _, o := range objects {
		if o.Name == name && isOther(o) {
			return graphObject(o), nil
		}
	}
	return nil, nil
}

// OtherTarget returns graph.OtherTargetResolver implementation.
func (r *Resolver) OtherTarget() graph.OtherTargetResolver { return &otherTargetResolver{r} }

type otherTargetResolver struct{ *Resolver }
