package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"

	"github.com/USA-RedDragon/astro-processing/internal/server/graph"
	"github.com/USA-RedDragon/astro-processing/internal/server/graph/model"
	"github.com/USA-RedDragon/astro-processing/internal/store/models/targetscheduler"
	"github.com/USA-RedDragon/astro-processing/internal/utils"
)

// Targets is the resolver for the targets field.
func (r *queryResolver) Targets(ctx context.Context, orderBy *model.TargetOrderBy) ([]*model.Target, error) {
	db := r.db.WithContext(ctx)

	// Apply ordering if provided
	if orderBy != nil {
		direction := "ASC"
		if orderBy.Direction == model.OrderDirectionDesc {
			direction = "DESC"
		}

		switch orderBy.Field {
		case model.TargetOrderFieldLastImageDate:
			// Special case: requires subquery
			db = db.Order(fmt.Sprintf(`(
				SELECT MAX(acquireddate) 
				FROM acquiredimage 
				WHERE acquiredimage."targetId" = target."Id"
			) %s NULLS LAST`, direction))
		case model.TargetOrderFieldProgress:
			// Special case: calculate progress as accepted/desired ratio
			db = db.Order(fmt.Sprintf(`(
				SELECT CASE 
					WHEN COALESCE(SUM(desired), 0) = 0 THEN 0 
					ELSE CAST(
						(SELECT COUNT(*) FROM acquiredimage WHERE "targetId" = target."Id" AND "gradingStatus" = 1) 
						AS FLOAT
					) / COALESCE(SUM(desired), 1)
				END
				FROM exposureplan
				WHERE targetid = target."Id"
			) %s NULLS LAST`, direction))
		case model.TargetOrderFieldName:
			db = db.Order(fmt.Sprintf("name %s", direction))
		case model.TargetOrderFieldActive:
			db = db.Order(fmt.Sprintf("active %s", direction))
		}
	}

	var targets []targetscheduler.Target
	if err := db.Find(&targets).Error; err != nil {
		return nil, err
	}

	var result []*model.Target
	for _, t := range targets {
		result = append(result, t.GraphQL())
	}
	return result, nil
}

// Target is the resolver for the target field.
func (r *queryResolver) Target(ctx context.Context, id int) (*model.Target, error) {
	db := r.db.WithContext(ctx)
	var target targetscheduler.Target
	if err := db.First(&target, id).Error; err != nil {
		return nil, err
	}
	return target.GraphQL(), nil
}

// Project is the resolver for the project field.
func (r *targetResolver) Project(ctx context.Context, obj *model.Target) (*model.Project, error) {
	db := r.db.WithContext(ctx)
	var project targetscheduler.Project
	if err := db.First(&project, obj.Project.ID).Error; err != nil {
		return nil, err
	}
	return project.GraphQL(), nil
}

// Stats is the resolver for the stats field.
func (r *targetResolver) Stats(ctx context.Context, obj *model.Target) (*model.TargetStats, error) {
	return &model.TargetStats{}, nil
}

// Subframes is the resolver for the subframes field.
func (r *targetResolver) Subframes(ctx context.Context, obj *model.Target) ([]*model.Subframe, error) {
	subs, err := r.targetSubframes(ctx, obj.ID, obj.Name)
	if err != nil {
		return nil, err
	}
	// Previews are optional: a worker outage shouldn't hide the subframes.
	var previews map[string]string
	if r.worker != nil {
		if previews, err = r.worker.Previews(ctx, obj.Name); err != nil {
			slog.Warn("Could not load subframe previews", "target", obj.Name, "error", err)
		}
	}
	out := make([]*model.Subframe, 0, len(subs))
	for _, s := range subs {
		m := toModelSubframe(s)
		if m.FileName != nil {
			if u, ok := previews[*m.FileName]; ok {
				m.PreviewURL = &u
			}
		}
		out = append(out, m)
	}
	return out, nil
}

// LastImageDate is the resolver for the last_image_date field.
func (r *targetStatsResolver) LastImageDate(ctx context.Context, obj *model.TargetStats) (*int32, error) {
	db := r.db.WithContext(ctx)

	target, err := utils.FindParent[*model.Target](ctx)
	if err != nil {
		return nil, fmt.Errorf("could not find parent target for last image date: %w", err)
	}

	var lastImageDate sql.NullInt64
	if err := db.Model(&targetscheduler.AcquiredImage{}).
		Where("\"targetId\" = ?", target.ID).
		Select("MAX(acquireddate)").
		Scan(&lastImageDate).Error; err != nil {
		return nil, fmt.Errorf("failed to get last image date: %w", err)
	}
	if lastImageDate.Valid {
		val := int32(lastImageDate.Int64)
		return &val, nil
	}
	return nil, nil
}

// Total is the resolver for the total field.
func (r *targetStatsResolver) Total(ctx context.Context, obj *model.TargetStats) (*model.ImagingStats, error) {
	db := r.db.WithContext(ctx)

	target, err := utils.FindParent[*model.Target](ctx)
	if err != nil {
		return nil, fmt.Errorf("could not find parent target for imaging stats: %w", err)
	}

	var acquiredCount int64
	if err := db.Model(&targetscheduler.AcquiredImage{}).
		Where("\"targetId\" = ?", target.ID).
		Count(&acquiredCount).Error; err != nil {
		return nil, fmt.Errorf("failed to count acquired images: %w", err)
	}

	var acceptedCount int64
	if err := db.Model(&targetscheduler.AcquiredImage{}).
		Where("\"targetId\" = ? AND \"gradingStatus\" = ?", target.ID, 1).
		Count(&acceptedCount).Error; err != nil {
		return nil, fmt.Errorf("failed to count accepted images: %w", err)
	}

	var rejectedCount int64
	if err := db.Model(&targetscheduler.AcquiredImage{}).
		Where("\"targetId\" = ? AND \"gradingStatus\" = ?", target.ID, 2).
		Count(&rejectedCount).Error; err != nil {
		return nil, fmt.Errorf("failed to count rejected images: %w", err)
	}

	var desiredCount int64
	if err := db.Model(&targetscheduler.ExposurePlan{}).
		Where("targetid = ?", target.ID).
		Select("COALESCE(SUM(desired), 0)").
		Scan(&desiredCount).Error; err != nil {
		return nil, fmt.Errorf("failed to sum desired exposures: %w", err)
	}

	return &model.ImagingStats{
		AcceptedImages: int32(acceptedCount),
		AcquiredImages: int32(acquiredCount),
		RejectedImages: int32(rejectedCount),
		DesiredImages:  int32(desiredCount),
	}, nil
}

// Filters is the resolver for the filters field.
func (r *targetStatsResolver) Filters(ctx context.Context, obj *model.TargetStats) ([]*model.TargetFilterStats, error) {
	db := r.db.WithContext(ctx)

	target, err := utils.FindParent[*model.Target](ctx)
	if err != nil {
		return nil, fmt.Errorf("could not find parent target for imaging stats: %w", err)
	}

	type planStats struct {
		PlanID          int
		FilterName      *string
		TemplateName    *string
		PlanExposure    *float64
		DefaultExposure *float64
		Enabled         *int
		Gain            *int32
		Offset          *int32
		AcquiredCount   int64
		AcceptedCount   int64
		RejectedCount   int64
		Desired         *int64
	}

	var rows []planStats

	imageCounts := db.Table("acquiredimage").
		Select(`"exposureId" as exposure_id,
			COUNT(*) as acquired,
			SUM(CASE WHEN "gradingStatus" = 1 THEN 1 ELSE 0 END) as accepted,
			SUM(CASE WHEN "gradingStatus" = 2 THEN 1 ELSE 0 END) as rejected`).
		Where("\"targetId\" = ?", target.ID).
		Group("exposure_id")

	if err := db.Table("exposureplan as ep").
		Select(`ep."Id" as plan_id,
			et.filtername as filter_name,
			et.name as template_name,
			ep.exposure as plan_exposure,
			et.defaultexposure as default_exposure,
			ep.enabled as enabled,
			et.gain,
			et.offset,
			COALESCE(ai.acquired, 0) as acquired_count,
			COALESCE(ai.accepted, 0) as accepted_count,
			COALESCE(ai.rejected, 0) as rejected_count,
			ep.desired as desired`).
		Joins("LEFT JOIN exposuretemplate et ON ep.\"exposureTemplateId\" = et.\"Id\"").
		Joins("LEFT JOIN (?) ai ON ai.exposure_id = ep.\"Id\"", imageCounts).
		Where("ep.targetid = ?", target.ID).
		Order("ep.\"Id\"").
		Scan(&rows).Error; err != nil {
		return nil, fmt.Errorf("failed to get plan stats: %w", err)
	}

	stats := make([]*model.TargetFilterStats, 0, len(rows))
	for _, ps := range rows {
		st := &model.TargetFilterStats{
			TemplateName: ps.TemplateName,
			Gain:         ps.Gain,
			Offset:       ps.Offset,
			Imaging: &model.ImagingStats{
				AcceptedImages: int32(ps.AcceptedCount),
				AcquiredImages: int32(ps.AcquiredCount),
				RejectedImages: int32(ps.RejectedCount),
			},
		}
		if ps.FilterName != nil {
			st.FilterName = *ps.FilterName
		}
		if ps.Desired != nil {
			st.Imaging.DesiredImages = int32(*ps.Desired)
		}
		if ps.Enabled != nil {
			on := *ps.Enabled != 0
			st.Enabled = &on
		}
		switch {
		case ps.PlanExposure != nil && *ps.PlanExposure > 0:
			st.Exposure, st.ExposureSource = ps.PlanExposure, optional("plan")
		case ps.DefaultExposure != nil:
			st.Exposure, st.ExposureSource = ps.DefaultExposure, optional("template")
		}
		stats = append(stats, st)
	}
	return stats, nil
}

// Quality is the resolver for the quality field.
func (r *targetStatsResolver) Quality(ctx context.Context, obj *model.TargetStats) ([]*model.FilterQuality, error) {
	target, err := utils.FindParent[*model.Target](ctx)
	if err != nil {
		return nil, fmt.Errorf("could not find parent target for quality stats: %w", err)
	}
	subs, err := r.targetSubframes(ctx, target.ID, target.Name)
	if err != nil {
		return nil, err
	}
	return summarizeQuality(subs), nil
}

// Calibration is the resolver for the calibration field.
func (r *targetResolver) Calibration(ctx context.Context, obj *model.Target) ([]*model.CalibrationRow, error) {
	if r.worker == nil {
		return []*model.CalibrationRow{}, nil
	}
	rows, err := r.worker.Coverage(ctx, obj.Name)
	if err != nil {
		return nil, fmt.Errorf("failed to get calibration coverage: %w", err)
	}
	out := make([]*model.CalibrationRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, toCalibrationRow(row))
	}
	return out, nil
}

// Masters is the resolver for the masters field.
func (r *targetResolver) Masters(ctx context.Context, obj *model.Target) ([]*model.FilterMaster, error) {
	if r.worker == nil {
		return []*model.FilterMaster{}, nil
	}
	return r.masters(ctx, obj.Name)
}

// Target returns graph.TargetResolver implementation.
func (r *Resolver) Target() graph.TargetResolver { return &targetResolver{r} }

// TargetStats returns graph.TargetStatsResolver implementation.
func (r *Resolver) TargetStats() graph.TargetStatsResolver { return &targetStatsResolver{r} }

type targetResolver struct{ *Resolver }
type targetStatsResolver struct{ *Resolver }
