// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	types "github.com/USA-RedDragon/astro-processing/internal/types"
	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type cORSShadow struct {
	Enabled          *bool     `json:"enabled"           toml:"enabled"           yaml:"enabled"`
	AllowedOrigins   *[]string `json:"allowed-origins"   toml:"allowed-origins"   yaml:"allowed-origins"`
	AllowedMethods   *[]string `json:"allowed-methods"   toml:"allowed-methods"   yaml:"allowed-methods"`
	AllowedHeaders   *[]string `json:"allowed-headers"   toml:"allowed-headers"   yaml:"allowed-headers"`
	AllowCredentials *bool     `json:"allow-credentials" toml:"allow-credentials" yaml:"allow-credentials"`
}

type hTTPShadow struct {
	Bind           *string     `json:"bind"            toml:"bind"            yaml:"bind"`
	Port           *int        `json:"port"            toml:"port"            yaml:"port"`
	TrustedProxies *[]string   `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
	CORS           *cORSShadow `json:"cors"            toml:"cors"            yaml:"cors"`
}

type metricsShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Bind    *string `json:"bind"    toml:"bind"    yaml:"bind"`
	Port    *int    `json:"port"    toml:"port"    yaml:"port"`
}

type pProfShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Bind    *string `json:"bind"    toml:"bind"    yaml:"bind"`
	Port    *int    `json:"port"    toml:"port"    yaml:"port"`
}

type storageShadow struct {
	Type *string `json:"type" toml:"type" yaml:"type"`
	DSN  *string `json:"dsn"  toml:"dsn"  yaml:"dsn"`
}

type workerShadow struct {
	URL *string `json:"url" toml:"url" yaml:"url"`
}

type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	HTTP     *hTTPShadow    `json:"http"      toml:"http"      yaml:"http"`
	Metrics  *metricsShadow `json:"metrics"   toml:"metrics"   yaml:"metrics"`
	PProf    *pProfShadow   `json:"pprof"     toml:"pprof"     yaml:"pprof"`
	Storage  *storageShadow `json:"storage"   toml:"storage"   yaml:"storage"`
	Worker   *workerShadow  `json:"worker"    toml:"worker"    yaml:"worker"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.HTTP.Bind = "[::]"
	set("http.bind", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	{
		lst := impl.SplitList("*", sep)
		cfg.HTTP.CORS.AllowedOrigins = lst
		set("http.cors.allowed-origins", configulator.LayerDefault, "default tag")
	}
	{
		lst := impl.SplitList("GET,POST,PUT,DELETE,OPTIONS", sep)
		cfg.HTTP.CORS.AllowedMethods = lst
		set("http.cors.allowed-methods", configulator.LayerDefault, "default tag")
	}
	{
		lst := impl.SplitList("Origin,Content-Type,Accept,Authorization", sep)
		cfg.HTTP.CORS.AllowedHeaders = lst
		set("http.cors.allowed-headers", configulator.LayerDefault, "default tag")
	}
	cfg.Metrics.Bind = "127.0.0.1"
	set("metrics.bind", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9000
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.PProf.Bind = "127.0.0.1"
	set("pprof.bind", configulator.LayerDefault, "default tag")
	cfg.PProf.Port = 9999
	set("pprof.port", configulator.LayerDefault, "default tag")
	cfg.Storage.Type = types.StorageType("sqlite")
	set("storage.type", configulator.LayerDefault, "default tag")
	cfg.Storage.DSN = ":memory:?_pragma=foreign_keys(1)"
	set("storage.dsn", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted-proxies", configulator.LayerFile, file)
		}
		if s.HTTP.CORS != nil {
			if s.HTTP.CORS.Enabled != nil {
				cfg.HTTP.CORS.Enabled = *s.HTTP.CORS.Enabled
				set("http.cors.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowedOrigins != nil {
				cfg.HTTP.CORS.AllowedOrigins = *s.HTTP.CORS.AllowedOrigins
				set("http.cors.allowed-origins", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowedMethods != nil {
				cfg.HTTP.CORS.AllowedMethods = *s.HTTP.CORS.AllowedMethods
				set("http.cors.allowed-methods", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowedHeaders != nil {
				cfg.HTTP.CORS.AllowedHeaders = *s.HTTP.CORS.AllowedHeaders
				set("http.cors.allowed-headers", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowCredentials != nil {
				cfg.HTTP.CORS.AllowCredentials = *s.HTTP.CORS.AllowCredentials
				set("http.cors.allow-credentials", configulator.LayerFile, file)
			}
		}
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Bind != nil {
			cfg.Metrics.Bind = *s.Metrics.Bind
			set("metrics.bind", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
		if s.PProf.Bind != nil {
			cfg.PProf.Bind = *s.PProf.Bind
			set("pprof.bind", configulator.LayerFile, file)
		}
		if s.PProf.Port != nil {
			cfg.PProf.Port = *s.PProf.Port
			set("pprof.port", configulator.LayerFile, file)
		}
	}
	if s.Storage != nil {
		if s.Storage.Type != nil {
			cfg.Storage.Type = types.StorageType(*s.Storage.Type)
			set("storage.type", configulator.LayerFile, file)
		}
		if s.Storage.DSN != nil {
			cfg.Storage.DSN = *s.Storage.DSN
			set("storage.dsn", configulator.LayerFile, file)
		}
	}
	if s.Worker != nil {
		if s.Worker.URL != nil {
			cfg.Worker.URL = *s.Worker.URL
			set("worker.url", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); ok {
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = int(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted-proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.TrustedProxies = lst
		set("http.trusted-proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.CORS.Enabled = p
		set("http.cors.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allowed-origins"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.CORS.AllowedOrigins = lst
		set("http.cors.allowed-origins", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allowed-methods"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.CORS.AllowedMethods = lst
		set("http.cors.allowed-methods", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allowed-headers"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.CORS.AllowedHeaders = lst
		set("http.cors.allowed-headers", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allow-credentials"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allow-credentials",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.CORS.AllowCredentials = p
		set("http.cors.allow-credentials", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Enabled = p
		set("metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "bind"); ok {
		cfg.Metrics.Bind = v
		set("metrics.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Port = int(p)
		set("metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Enabled = p
		set("pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "bind"); ok {
		cfg.PProf.Bind = v
		set("pprof.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Port = int(p)
		set("pprof.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "storage", "type"); ok {
		cfg.Storage.Type = types.StorageType(v)
		set("storage.type", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "storage", "dsn"); ok {
		cfg.Storage.DSN = v
		set("storage.dsn", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "worker", "url"); ok {
		cfg.Worker.URL = v
		set("worker.url", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"http" + o.Separator + "bind",
		"http" + o.Separator + "port",
		"http" + o.Separator + "trusted-proxies",
		"http" + o.Separator + "cors" + o.Separator + "enabled",
		"http" + o.Separator + "cors" + o.Separator + "allowed-origins",
		"http" + o.Separator + "cors" + o.Separator + "allowed-methods",
		"http" + o.Separator + "cors" + o.Separator + "allowed-headers",
		"http" + o.Separator + "cors" + o.Separator + "allow-credentials",
		"metrics" + o.Separator + "enabled",
		"metrics" + o.Separator + "bind",
		"metrics" + o.Separator + "port",
		"pprof" + o.Separator + "enabled",
		"pprof" + o.Separator + "bind",
		"pprof" + o.Separator + "port",
		"storage" + o.Separator + "type",
		"storage" + o.Separator + "dsn",
		"worker" + o.Separator + "url",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(names[1], "[::]", "Address to listen on")
	fs.Var(impl.NewInt(8080), names[2], "Port to listen on")
	fs.StringSlice(names[3], nil, "Trusted proxy IPs whose X-Forwarded-* headers are honored")
	fs.Bool(names[4], false, "Enable CORS")
	fs.StringSlice(names[5], nil, "List of allowed origins for CORS")
	fs.Lookup(names[5]).DefValue = "[*]"
	fs.StringSlice(names[6], nil, "List of allowed HTTP methods for CORS")
	fs.Lookup(names[6]).DefValue = "[GET,POST,PUT,DELETE,OPTIONS]"
	fs.StringSlice(names[7], nil, "List of allowed HTTP headers for CORS")
	fs.Lookup(names[7]).DefValue = "[Origin,Content-Type,Accept,Authorization]"
	fs.Bool(names[8], false, "Allow credentials for CORS")
	fs.Bool(names[9], false, "Enable metrics server")
	fs.String(names[10], "127.0.0.1", "Address to listen on")
	fs.Var(impl.NewInt(9000), names[11], "Port to listen on")
	fs.Bool(names[12], false, "Enable pprof server")
	fs.String(names[13], "127.0.0.1", "Address to listen on")
	fs.Var(impl.NewInt(9999), names[14], "Port to listen on")
	fs.String(names[15], "sqlite", "Storage type. One of mysql, postgres, sqlite")
	fs.String(names[16], ":memory:?_pragma=foreign_keys(1)", "Data source name for the storage, for example file:database.db?_pragma=foreign_keys(1)&journal_mode=WAL (sqlite), host=localhost user=username dbname=database password=password sslmode=disable (postgres) or username:password@tcp(localhost:3306)/database?charset=utf8&parseTime=True (mysql)")
	fs.String(names[17], "", "Base URL of pixinsight-worker, for calibration coverage. Empty disables it")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "trusted-proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.Enabled = v
		set("http.cors.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "allowed-origins"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allowed-origins",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowedOrigins = v
		set("http.cors.allowed-origins", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "allowed-methods"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allowed-methods",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowedMethods = v
		set("http.cors.allowed-methods", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "allowed-headers"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allowed-headers",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowedHeaders = v
		set("http.cors.allowed-headers", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "cors" + o.Separator + "allow-credentials"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allow-credentials",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowCredentials = v
		set("http.cors.allow-credentials", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.bind",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Bind = v
		set("metrics.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.bind",
				Source: "--" + n,
			}
		}
		cfg.PProf.Bind = v
		set("pprof.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: "--" + n,
			}
		}
		cfg.PProf.Port = v
		set("pprof.port", configulator.LayerCLI, "--"+n)
	}
	if n := "storage" + o.Separator + "type"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.type",
				Source: "--" + n,
			}
		}
		cfg.Storage.Type = types.StorageType(v)
		set("storage.type", configulator.LayerCLI, "--"+n)
	}
	if n := "storage" + o.Separator + "dsn"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.dsn",
				Source: "--" + n,
			}
		}
		cfg.Storage.DSN = v
		set("storage.dsn", configulator.LayerCLI, "--"+n)
	}
	if n := "worker" + o.Separator + "url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "worker.url",
				Source: "--" + n,
			}
		}
		cfg.Worker.URL = v
		set("worker.url", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, "metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, "pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "storage":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("storage", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub storageShadow
				if err := sub.decodeJSON(dec, "storage"); err != nil {
					return err
				}
				s.Storage = &sub
			}
		case "worker":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("worker", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub workerShadow
				if err := sub.decodeJSON(dec, "worker"); err != nil {
					return err
				}
				s.Worker = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "trusted-proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted-proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted-proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "cors":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".cors", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub cORSShadow
				if err := sub.decodeJSON(dec, path+".cors"); err != nil {
					return err
				}
				s.CORS = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *cORSShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "allowed-origins":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".allowed-origins", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".allowed-origins"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.AllowedOrigins = &out
			}
		case "allowed-methods":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".allowed-methods", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".allowed-methods"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.AllowedMethods = &out
			}
		case "allowed-headers":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".allowed-headers", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".allowed-headers"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.AllowedHeaders = &out
			}
		case "allow-credentials":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.AllowCredentials = &b
			default:
				return configJSONError(path+".allow-credentials", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *storageShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "type":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Type = &str
			default:
				return configJSONError(path+".type", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "dsn":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.DSN = &str
			default:
				return configJSONError(path+".dsn", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *workerShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.URL = &str
			default:
				return configJSONError(path+".url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "http.bind = %v\n", c.HTTP.Bind)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "http.trusted-proxies = %v\n", c.HTTP.TrustedProxies)
	fmt.Fprintf(&b, "http.cors.enabled = %v\n", c.HTTP.CORS.Enabled)
	fmt.Fprintf(&b, "http.cors.allowed-origins = %v\n", c.HTTP.CORS.AllowedOrigins)
	fmt.Fprintf(&b, "http.cors.allowed-methods = %v\n", c.HTTP.CORS.AllowedMethods)
	fmt.Fprintf(&b, "http.cors.allowed-headers = %v\n", c.HTTP.CORS.AllowedHeaders)
	fmt.Fprintf(&b, "http.cors.allow-credentials = %v\n", c.HTTP.CORS.AllowCredentials)
	fmt.Fprintf(&b, "metrics.enabled = %v\n", c.Metrics.Enabled)
	fmt.Fprintf(&b, "metrics.bind = %v\n", c.Metrics.Bind)
	fmt.Fprintf(&b, "metrics.port = %v\n", c.Metrics.Port)
	fmt.Fprintf(&b, "pprof.enabled = %v\n", c.PProf.Enabled)
	fmt.Fprintf(&b, "pprof.bind = %v\n", c.PProf.Bind)
	fmt.Fprintf(&b, "pprof.port = %v\n", c.PProf.Port)
	fmt.Fprintf(&b, "storage.type = %v\n", c.Storage.Type)
	fmt.Fprintf(&b, "storage.dsn = %v\n", c.Storage.DSN)
	fmt.Fprintf(&b, "worker.url = %v\n", c.Worker.URL)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
