// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	types "github.com/USA-RedDragon/astro-processing/internal/types"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type cORSShadow struct {
	Enabled          *bool     `json:"enabled" toml:"enabled" yaml:"enabled"`
	AllowedOrigins   *[]string `json:"allowed-origins" toml:"allowed-origins" yaml:"allowed-origins"`
	AllowedMethods   *[]string `json:"allowed-methods" toml:"allowed-methods" yaml:"allowed-methods"`
	AllowedHeaders   *[]string `json:"allowed-headers" toml:"allowed-headers" yaml:"allowed-headers"`
	AllowCredentials *bool     `json:"allow-credentials" toml:"allow-credentials" yaml:"allow-credentials"`
}
type hTTPShadow struct {
	Bind           *string     `json:"bind" toml:"bind" yaml:"bind"`
	Port           *int        `json:"port" toml:"port" yaml:"port"`
	TrustedProxies *[]string   `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
	CORS           *cORSShadow `json:"cors" toml:"cors" yaml:"cors"`
}
type metricsShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Bind    *string `json:"bind" toml:"bind" yaml:"bind"`
	Port    *int    `json:"port" toml:"port" yaml:"port"`
}
type pProfShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Bind    *string `json:"bind" toml:"bind" yaml:"bind"`
	Port    *int    `json:"port" toml:"port" yaml:"port"`
}
type storageShadow struct {
	Type *string `json:"type" toml:"type" yaml:"type"`
	DSN  *string `json:"dsn" toml:"dsn" yaml:"dsn"`
}
type qualityShadow struct {
	Pedestal *float64 `json:"pedestal" toml:"pedestal" yaml:"pedestal"`
}
type workerShadow struct {
	URL *string `json:"url" toml:"url" yaml:"url"`
}
type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	HTTP     *hTTPShadow    `json:"http" toml:"http" yaml:"http"`
	Metrics  *metricsShadow `json:"metrics" toml:"metrics" yaml:"metrics"`
	PProf    *pProfShadow   `json:"pprof" toml:"pprof" yaml:"pprof"`
	Storage  *storageShadow `json:"storage" toml:"storage" yaml:"storage"`
	Quality  *qualityShadow `json:"quality" toml:"quality" yaml:"quality"`
	Worker   *workerShadow  `json:"worker" toml:"worker" yaml:"worker"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.HTTP.Bind = "[::]"
	set("http.bind", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.HTTP.CORS.AllowedOrigins = []string{"*"}
	set("http.cors.allowed-origins", configulator.LayerDefault, "default tag")
	cfg.HTTP.CORS.AllowedMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	set("http.cors.allowed-methods", configulator.LayerDefault, "default tag")
	cfg.HTTP.CORS.AllowedHeaders = []string{"Origin", "Content-Type", "Accept", "Authorization"}
	set("http.cors.allowed-headers", configulator.LayerDefault, "default tag")
	cfg.Metrics.Bind = "127.0.0.1"
	set("metrics.bind", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9000
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.PProf.Bind = "127.0.0.1"
	set("pprof.bind", configulator.LayerDefault, "default tag")
	cfg.PProf.Port = 9999
	set("pprof.port", configulator.LayerDefault, "default tag")
	cfg.Storage.Type = types.StorageType("sqlite")
	set("storage.type", configulator.LayerDefault, "default tag")
	cfg.Storage.DSN = ":memory:?_pragma=foreign_keys(1)"
	set("storage.dsn", configulator.LayerDefault, "default tag")
	cfg.Quality.Pedestal = 506.0
	set("quality.pedestal", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted-proxies", configulator.LayerFile, file)
		}
		if s.HTTP.CORS != nil {
			if s.HTTP.CORS.Enabled != nil {
				cfg.HTTP.CORS.Enabled = *s.HTTP.CORS.Enabled
				set("http.cors.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowedOrigins != nil {
				cfg.HTTP.CORS.AllowedOrigins = *s.HTTP.CORS.AllowedOrigins
				set("http.cors.allowed-origins", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowedMethods != nil {
				cfg.HTTP.CORS.AllowedMethods = *s.HTTP.CORS.AllowedMethods
				set("http.cors.allowed-methods", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowedHeaders != nil {
				cfg.HTTP.CORS.AllowedHeaders = *s.HTTP.CORS.AllowedHeaders
				set("http.cors.allowed-headers", configulator.LayerFile, file)
			}
			if s.HTTP.CORS.AllowCredentials != nil {
				cfg.HTTP.CORS.AllowCredentials = *s.HTTP.CORS.AllowCredentials
				set("http.cors.allow-credentials", configulator.LayerFile, file)
			}
		}
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Bind != nil {
			cfg.Metrics.Bind = *s.Metrics.Bind
			set("metrics.bind", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
		if s.PProf.Bind != nil {
			cfg.PProf.Bind = *s.PProf.Bind
			set("pprof.bind", configulator.LayerFile, file)
		}
		if s.PProf.Port != nil {
			cfg.PProf.Port = *s.PProf.Port
			set("pprof.port", configulator.LayerFile, file)
		}
	}
	if s.Storage != nil {
		if s.Storage.Type != nil {
			cfg.Storage.Type = types.StorageType(*s.Storage.Type)
			set("storage.type", configulator.LayerFile, file)
		}
		if s.Storage.DSN != nil {
			cfg.Storage.DSN = *s.Storage.DSN
			set("storage.dsn", configulator.LayerFile, file)
		}
	}
	if s.Quality != nil {
		if s.Quality.Pedestal != nil {
			cfg.Quality.Pedestal = *s.Quality.Pedestal
			set("quality.pedestal", configulator.LayerFile, file)
		}
	}
	if s.Worker != nil {
		if s.Worker.URL != nil {
			cfg.Worker.URL = *s.Worker.URL
			set("worker.url", configulator.LayerFile, file)
		}
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Bind = v
			set("http.bind", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.Port = int(p)
			set("http.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted-proxies"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.TrustedProxies = configulator.SplitList(v, ec.ArraySeparator)
			set("http.trusted-proxies", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.cors.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.CORS.Enabled = p
			set("http.cors.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allowed-origins"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.CORS.AllowedOrigins = configulator.SplitList(v, ec.ArraySeparator)
			set("http.cors.allowed-origins", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allowed-methods"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.CORS.AllowedMethods = configulator.SplitList(v, ec.ArraySeparator)
			set("http.cors.allowed-methods", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allowed-headers"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.CORS.AllowedHeaders = configulator.SplitList(v, ec.ArraySeparator)
			set("http.cors.allowed-headers", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "cors", "allow-credentials"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.cors.allow-credentials",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.CORS.AllowCredentials = p
			set("http.cors.allow-credentials", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Enabled = p
			set("metrics.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "bind"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Metrics.Bind = v
			set("metrics.bind", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Port = int(p)
			set("metrics.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "pprof.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.PProf.Enabled = p
			set("pprof.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "bind"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.PProf.Bind = v
			set("pprof.bind", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "pprof.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.PProf.Port = int(p)
			set("pprof.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "storage", "type"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Storage.Type = types.StorageType(v)
			set("storage.type", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "storage", "dsn"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Storage.DSN = v
			set("storage.dsn", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "quality", "pedestal"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "quality.pedestal",
					Source: n,
					Value:  v,
				}
			}
			cfg.Quality.Pedestal = p
			set("quality.pedestal", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "worker", "url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Worker.URL = v
			set("worker.url", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"http", "bind"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator), strings.Join([]string{"http", "trusted-proxies"}, o.Separator), strings.Join([]string{"http", "cors", "enabled"}, o.Separator), strings.Join([]string{"http", "cors", "allowed-origins"}, o.Separator), strings.Join([]string{"http", "cors", "allowed-methods"}, o.Separator), strings.Join([]string{"http", "cors", "allowed-headers"}, o.Separator), strings.Join([]string{"http", "cors", "allow-credentials"}, o.Separator), strings.Join([]string{"metrics", "enabled"}, o.Separator), strings.Join([]string{"metrics", "bind"}, o.Separator), strings.Join([]string{"metrics", "port"}, o.Separator), strings.Join([]string{"pprof", "enabled"}, o.Separator), strings.Join([]string{"pprof", "bind"}, o.Separator), strings.Join([]string{"pprof", "port"}, o.Separator), strings.Join([]string{"storage", "type"}, o.Separator), strings.Join([]string{"storage", "dsn"}, o.Separator), strings.Join([]string{"quality", "pedestal"}, o.Separator), strings.Join([]string{"worker", "url"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(strings.Join([]string{"http", "bind"}, o.Separator), "[::]", "Address to listen on")
	fs.Int(strings.Join([]string{"http", "port"}, o.Separator), 8080, "Port to listen on")
	fs.StringSlice(strings.Join([]string{"http", "trusted-proxies"}, o.Separator), nil, "Trusted proxies for the HTTP server")
	fs.Bool(strings.Join([]string{"http", "cors", "enabled"}, o.Separator), false, "Enable CORS")
	fs.StringSlice(strings.Join([]string{"http", "cors", "allowed-origins"}, o.Separator), []string{"*"}, "List of allowed origins for CORS")
	fs.StringSlice(strings.Join([]string{"http", "cors", "allowed-methods"}, o.Separator), []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}, "List of allowed HTTP methods for CORS")
	fs.StringSlice(strings.Join([]string{"http", "cors", "allowed-headers"}, o.Separator), []string{"Origin", "Content-Type", "Accept", "Authorization"}, "List of allowed HTTP headers for CORS")
	fs.Bool(strings.Join([]string{"http", "cors", "allow-credentials"}, o.Separator), false, "Allow credentials for CORS")
	fs.Bool(strings.Join([]string{"metrics", "enabled"}, o.Separator), false, "Enable metrics server")
	fs.String(strings.Join([]string{"metrics", "bind"}, o.Separator), "127.0.0.1", "Address to listen on")
	fs.Int(strings.Join([]string{"metrics", "port"}, o.Separator), 9000, "Port to listen on")
	fs.Bool(strings.Join([]string{"pprof", "enabled"}, o.Separator), false, "Enable pprof server")
	fs.String(strings.Join([]string{"pprof", "bind"}, o.Separator), "127.0.0.1", "Address to listen on")
	fs.Int(strings.Join([]string{"pprof", "port"}, o.Separator), 9999, "Port to listen on")
	fs.String(strings.Join([]string{"storage", "type"}, o.Separator), "sqlite", "Storage type. One of mysql, postgres, sqlite")
	fs.String(strings.Join([]string{"storage", "dsn"}, o.Separator), ":memory:?_pragma=foreign_keys(1)", "Data source name for the storage")
	fs.Float64(strings.Join([]string{"quality", "pedestal"}, o.Separator), 506.0, "Camera pedestal in ADU at offset 50, adjusted for each sub's offset and subtracted from its ADU median to show the sky background")
	fs.String(strings.Join([]string{"worker", "url"}, o.Separator), "", "Base URL of pixinsight-worker, for calibration coverage. Empty disables it")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "bind"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "trusted-proxies"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "cors", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.Enabled = v
		set("http.cors.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "cors", "allowed-origins"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allowed-origins",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowedOrigins = v
		set("http.cors.allowed-origins", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "cors", "allowed-methods"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allowed-methods",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowedMethods = v
		set("http.cors.allowed-methods", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "cors", "allowed-headers"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allowed-headers",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowedHeaders = v
		set("http.cors.allowed-headers", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "cors", "allow-credentials"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.cors.allow-credentials",
				Source: "--" + n,
			}
		}
		cfg.HTTP.CORS.AllowCredentials = v
		set("http.cors.allow-credentials", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "bind"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.bind",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Bind = v
		set("metrics.bind", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "bind"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.bind",
				Source: "--" + n,
			}
		}
		cfg.PProf.Bind = v
		set("pprof.bind", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: "--" + n,
			}
		}
		cfg.PProf.Port = v
		set("pprof.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"storage", "type"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.type",
				Source: "--" + n,
			}
		}
		cfg.Storage.Type = types.StorageType(v)
		set("storage.type", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"storage", "dsn"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.dsn",
				Source: "--" + n,
			}
		}
		cfg.Storage.DSN = v
		set("storage.dsn", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"quality", "pedestal"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "quality.pedestal",
				Source: "--" + n,
			}
		}
		cfg.Quality.Pedestal = v
		set("quality.pedestal", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"worker", "url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "worker.url",
				Source: "--" + n,
			}
		}
		cfg.Worker.URL = v
		set("worker.url", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub hTTPShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "metrics":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub metricsShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "pprof":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub pProfShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "storage":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub storageShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Storage = &sub
			}
		case "quality":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub qualityShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Quality = &sub
			}
		case "worker":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub workerShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Worker = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *hTTPShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Bind = &str
			default:
				return fmt.Errorf("bind: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "trusted-proxies":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("trusted-proxies: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("trusted-proxies: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "cors":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub cORSShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.CORS = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*hTTPShadow)(nil)

func (s *cORSShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "allowed-origins":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("allowed-origins: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("allowed-origins: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.AllowedOrigins = &out
			}
		case "allowed-methods":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("allowed-methods: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("allowed-methods: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.AllowedMethods = &out
			}
		case "allowed-headers":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("allowed-headers: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("allowed-headers: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.AllowedHeaders = &out
			}
		case "allow-credentials":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.AllowCredentials = &b
			default:
				return fmt.Errorf("allow-credentials: expected a bool, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*cORSShadow)(nil)

func (s *metricsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Bind = &str
			default:
				return fmt.Errorf("bind: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*metricsShadow)(nil)

func (s *pProfShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Bind = &str
			default:
				return fmt.Errorf("bind: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*pProfShadow)(nil)

func (s *storageShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "type":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Type = &str
			default:
				return fmt.Errorf("type: expected a string, got %v", v.Kind())
			}
		case "dsn":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.DSN = &str
			default:
				return fmt.Errorf("dsn: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*storageShadow)(nil)

func (s *qualityShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "pedestal":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.Pedestal = &val
			default:
				return fmt.Errorf("pedestal: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*qualityShadow)(nil)

func (s *workerShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.URL = &str
			default:
				return fmt.Errorf("url: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*workerShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("http.bind = %v\n", c.HTTP.Bind))
	b.WriteString(fmt.Sprintf("http.port = %v\n", c.HTTP.Port))
	b.WriteString(fmt.Sprintf("http.trusted-proxies = %v\n", c.HTTP.TrustedProxies))
	b.WriteString(fmt.Sprintf("http.cors.enabled = %v\n", c.HTTP.CORS.Enabled))
	b.WriteString(fmt.Sprintf("http.cors.allowed-origins = %v\n", c.HTTP.CORS.AllowedOrigins))
	b.WriteString(fmt.Sprintf("http.cors.allowed-methods = %v\n", c.HTTP.CORS.AllowedMethods))
	b.WriteString(fmt.Sprintf("http.cors.allowed-headers = %v\n", c.HTTP.CORS.AllowedHeaders))
	b.WriteString(fmt.Sprintf("http.cors.allow-credentials = %v\n", c.HTTP.CORS.AllowCredentials))
	b.WriteString(fmt.Sprintf("metrics.enabled = %v\n", c.Metrics.Enabled))
	b.WriteString(fmt.Sprintf("metrics.bind = %v\n", c.Metrics.Bind))
	b.WriteString(fmt.Sprintf("metrics.port = %v\n", c.Metrics.Port))
	b.WriteString(fmt.Sprintf("pprof.enabled = %v\n", c.PProf.Enabled))
	b.WriteString(fmt.Sprintf("pprof.bind = %v\n", c.PProf.Bind))
	b.WriteString(fmt.Sprintf("pprof.port = %v\n", c.PProf.Port))
	b.WriteString(fmt.Sprintf("storage.type = %v\n", c.Storage.Type))
	b.WriteString(fmt.Sprintf("storage.dsn = %v\n", c.Storage.DSN))
	b.WriteString(fmt.Sprintf("quality.pedestal = %v\n", c.Quality.Pedestal))
	b.WriteString(fmt.Sprintf("worker.url = %v\n", c.Worker.URL))
	return b.String()
}
