name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  frontend:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@86546533e7fe42b748a54ea123c6aa4e3e812241 # v2.0.31
    with:
      push: true
      image-name: usa-reddragon/astro-processing-frontend
      dockerfile: docker/frontend/Dockerfile
      version: ${{ github.ref_name == 'main' && 'beta' || '' }}

  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@86546533e7fe42b748a54ea123c6aa4e3e812241 # v2.0.31
    with:
      beta: ${{ github.ref_name == 'main' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
